//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actual_Production_Equipment_Qty
    {
        public int Actual_Production_Equipment_Qty_UID { get; set; }
        public int RP_Flowchart_Detail_ME_Equipment_UID { get; set; }
        public System.DateTime Production_Date { get; set; }
        public int Production_Qty { get; set; }
        public int Created_UID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual RP_Flowchart_Detail_ME_Equipment RP_Flowchart_Detail_ME_Equipment { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
