//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Electrical_Board_DT
    {
        public int Board_UID { get; set; }
        public string Project { get; set; }
        public string Part_Types { get; set; }
        public int FlowChart_Master_UID { get; set; }
        public string Time_Interval { get; set; }
        public string FunPlant { get; set; }
        public string Process { get; set; }
        public short Process_Seq { get; set; }
        public string DRI { get; set; }
        public int Prouct_Plan { get; set; }
        public double Target_Yield { get; set; }
        public int Picking_QTY { get; set; }
        public int WH_Picking_QTY { get; set; }
        public int Good_QTY { get; set; }
        public int Adjust_QTY { get; set; }
        public int WH_QTY { get; set; }
        public int NG_QTY { get; set; }
        public int WIP_QTY { get; set; }
        public string Color { get; set; }
        public string Flag { get; set; }
        public string Place { get; set; }
        public Nullable<bool> IsDiffLocation { get; set; }
    
        public virtual FlowChart_Master FlowChart_Master { get; set; }
    }
}
