//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enumeration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enumeration()
        {
            this.Material_Spareparts_Demand = new HashSet<Material_Spareparts_Demand>();
            this.Storage_Outbound_M = new HashSet<Storage_Outbound_M>();
            this.Storage_Outbound_M1 = new HashSet<Storage_Outbound_M>();
            this.Warehouse = new HashSet<Warehouse>();
            this.Material_Repair_Demand = new HashSet<Material_Repair_Demand>();
            this.Material_Demand_Summary = new HashSet<Material_Demand_Summary>();
            this.Material_Normal_Demand = new HashSet<Material_Normal_Demand>();
            this.Storage_Check = new HashSet<Storage_Check>();
            this.Storage_Check1 = new HashSet<Storage_Check>();
            this.Storage_Check2 = new HashSet<Storage_Check>();
            this.Storage_Inbound = new HashSet<Storage_Inbound>();
            this.Storage_Inbound1 = new HashSet<Storage_Inbound>();
            this.Storage_Inbound2 = new HashSet<Storage_Inbound>();
            this.Storage_InOut_Detail = new HashSet<Storage_InOut_Detail>();
            this.Storage_Transfer = new HashSet<Storage_Transfer>();
            this.Storage_Transfer1 = new HashSet<Storage_Transfer>();
            this.Storage_Outbound_D = new HashSet<Storage_Outbound_D>();
            this.Fixture_Repair_D = new HashSet<Fixture_Repair_D>();
            this.Fixture_Storage_InOut_Detail = new HashSet<Fixture_Storage_InOut_Detail>();
            this.Fixture_Storage_Transfer = new HashSet<Fixture_Storage_Transfer>();
            this.Fixture_Storage_Inbound = new HashSet<Fixture_Storage_Inbound>();
            this.Fixture_Storage_Inbound1 = new HashSet<Fixture_Storage_Inbound>();
            this.Fixture_Storage_Outbound_M = new HashSet<Fixture_Storage_Outbound_M>();
            this.Fixture_Storage_Outbound_M1 = new HashSet<Fixture_Storage_Outbound_M>();
            this.Fixture_Part_Demand_M = new HashSet<Fixture_Part_Demand_M>();
            this.Fixture_Part_Demand_Summary_M = new HashSet<Fixture_Part_Demand_Summary_M>();
            this.Fixture_Storage_Check = new HashSet<Fixture_Storage_Check>();
            this.Fixture_Storage_Check1 = new HashSet<Fixture_Storage_Check>();
            this.Fixture_M = new HashSet<Fixture_M>();
        }
    
        public int Enum_UID { get; set; }
        public string Enum_Type { get; set; }
        public string Enum_Name { get; set; }
        public string Enum_Value { get; set; }
        public string Decription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Spareparts_Demand> Material_Spareparts_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Outbound_M> Storage_Outbound_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Outbound_M> Storage_Outbound_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Repair_Demand> Material_Repair_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Demand_Summary> Material_Demand_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Normal_Demand> Material_Normal_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Check> Storage_Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Check> Storage_Check1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Check> Storage_Check2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Inbound> Storage_Inbound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Inbound> Storage_Inbound1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Inbound> Storage_Inbound2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_InOut_Detail> Storage_InOut_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Transfer> Storage_Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Transfer> Storage_Transfer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Outbound_D> Storage_Outbound_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_D> Fixture_Repair_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_InOut_Detail> Fixture_Storage_InOut_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Transfer> Fixture_Storage_Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Inbound> Fixture_Storage_Inbound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Inbound> Fixture_Storage_Inbound1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Outbound_M> Fixture_Storage_Outbound_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Outbound_M> Fixture_Storage_Outbound_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_M> Fixture_Part_Demand_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_Summary_M> Fixture_Part_Demand_Summary_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Check> Fixture_Storage_Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Check> Fixture_Storage_Check1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_M> Fixture_M { get; set; }
    }
}
