//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQP_UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQP_UserTable()
        {
            this.Labor_UsingInfo = new HashSet<Labor_UsingInfo>();
            this.Storage_Outbound_M = new HashSet<Storage_Outbound_M>();
        }
    
        public int EQPUser_Uid { get; set; }
        public Nullable<int> BG_Organization_UID { get; set; }
        public Nullable<int> FunPlant_Organization_UID { get; set; }
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_IdAndName { get; set; }
        public string User_Call { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string User_Email { get; set; }
        public int Plant_OrganizationUID { get; set; }
        public int IsDisable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Labor_UsingInfo> Labor_UsingInfo { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Outbound_M> Storage_Outbound_M { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
