//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment_Info()
        {
            this.CNCMachine = new HashSet<CNCMachine>();
            this.Meterial_UpdateInfo = new HashSet<Meterial_UpdateInfo>();
            this.OEE_MachineInfo = new HashSet<OEE_MachineInfo>();
            this.EQPRepair_Info = new HashSet<EQPRepair_Info>();
        }
    
        public int EQP_Uid { get; set; }
        public int System_FunPlant_UID { get; set; }
        public Nullable<int> Project_UID { get; set; }
        public string Process { get; set; }
        public string CoCd { get; set; }
        public string OpU { get; set; }
        public string C { get; set; }
        public string Process_Group { get; set; }
        public string Class { get; set; }
        public string Class_Desc { get; set; }
        public string Mfg_Of_Asset { get; set; }
        public string Model_Number { get; set; }
        public string Mfg_Serial_Num { get; set; }
        public string Mfg_Part_Number { get; set; }
        public string Equipment { get; set; }
        public string Asset { get; set; }
        public string User_Status { get; set; }
        public string AM_CostCtr { get; set; }
        public string Description_1 { get; set; }
        public Nullable<System.DateTime> Cap_date { get; set; }
        public decimal Acquisition_Value { get; set; }
        public int Asset_Life { get; set; }
        public decimal Net_Book_Value { get; set; }
        public decimal Monthly_Depreciation { get; set; }
        public int Remaining_Life { get; set; }
        public string Func_Loc { get; set; }
        public string Room { get; set; }
        public string MCtry { get; set; }
        public decimal Weight { get; set; }
        public string Un { get; set; }
        public string Size_dimension { get; set; }
        public string ConY { get; set; }
        public string CM { get; set; }
        public string Int_Note_L2 { get; set; }
        public string Description_2 { get; set; }
        public string Characteristic_1 { get; set; }
        public string Description_3 { get; set; }
        public string Characteristic_2 { get; set; }
        public string Description_4 { get; set; }
        public string Characteristic_3 { get; set; }
        public string Description_5 { get; set; }
        public string Characteristic_4 { get; set; }
        public string Description_6 { get; set; }
        public string Characteristic_5 { get; set; }
        public string Int_Note_L1 { get; set; }
        public string EQP_Plant_No { get; set; }
        public string EQP_Location { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public int Plant_Organization_UID { get; set; }
        public int BG_Organization_UID { get; set; }
        public Nullable<int> FunPlant_Organization_UID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNCMachine> CNCMachine { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        public virtual System_Organization System_Organization1 { get; set; }
        public virtual System_Organization System_Organization2 { get; set; }
        public virtual System_Function_Plant System_Function_Plant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meterial_UpdateInfo> Meterial_UpdateInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineInfo> OEE_MachineInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQPRepair_Info> EQPRepair_Info { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
