//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fixture_M()
        {
            this.Fixture_Maintenance_Record_History = new HashSet<Fixture_Maintenance_Record_History>();
            this.Fixture_Maintenance_Record = new HashSet<Fixture_Maintenance_Record>();
            this.Fixture_Repair_D = new HashSet<Fixture_Repair_D>();
            this.Fixture_Resume_History = new HashSet<Fixture_Resume_History>();
            this.Fixture_Resume = new HashSet<Fixture_Resume>();
            this.Fixture_Totake_D = new HashSet<Fixture_Totake_D>();
            this.Fixture_M_UseScanHistory = new HashSet<Fixture_M_UseScanHistory>();
            this.Fixture_Part_UseTimes = new HashSet<Fixture_Part_UseTimes>();
            this.Fixture_Return_D = new HashSet<Fixture_Return_D>();
        }
    
        public int Fixture_M_UID { get; set; }
        public int Plant_Organization_UID { get; set; }
        public int BG_Organization_UID { get; set; }
        public Nullable<int> FunPlant_Organization_UID { get; set; }
        public string Fixture_NO { get; set; }
        public string Version { get; set; }
        public string Fixture_Seq { get; set; }
        public string Fixture_Unique_ID { get; set; }
        public string Fixture_Name { get; set; }
        public Nullable<int> Project_UID { get; set; }
        public Nullable<int> Fixture_Machine_UID { get; set; }
        public Nullable<int> Vendor_Info_UID { get; set; }
        public Nullable<int> Production_Line_UID { get; set; }
        public int Status { get; set; }
        public string ShortCode { get; set; }
        public string TwoD_Barcode { get; set; }
        public int Created_UID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public Nullable<int> UseTimesTotal { get; set; }
    
        public virtual Enumeration Enumeration { get; set; }
        public virtual Production_Line Production_Line { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        public virtual System_Organization System_Organization1 { get; set; }
        public virtual System_Organization System_Organization2 { get; set; }
        public virtual System_Project System_Project { get; set; }
        public virtual Vendor_Info Vendor_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Record_History> Fixture_Maintenance_Record_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Record> Fixture_Maintenance_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_D> Fixture_Repair_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Resume_History> Fixture_Resume_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Resume> Fixture_Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Totake_D> Fixture_Totake_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_M_UseScanHistory> Fixture_M_UseScanHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_UseTimes> Fixture_Part_UseTimes { get; set; }
        public virtual Fixture_Machine Fixture_Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Return_D> Fixture_Return_D { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
