//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture_M_UseScanHistory
    {
        public int Fixture_M_UseScanHistory_UID { get; set; }
        public int Fixture_M_UID { get; set; }
        public int UseTimesTotal { get; set; }
        public bool IsValidSan { get; set; }
        public System.DateTime ScanDateTime { get; set; }
    
        public virtual Fixture_M Fixture_M { get; set; }
    }
}
