//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture_Storage_Outbound_D
    {
        public int Fixture_Storage_Outbound_D_UID { get; set; }
        public int Fixture_Storage_Outbound_M_UID { get; set; }
        public int Fixture_Part_UID { get; set; }
        public int Fixture_Warehouse_Storage_UID { get; set; }
        public decimal Outbound_Qty { get; set; }
        public string Remarks { get; set; }
    
        public virtual Fixture_Warehouse_Storage Fixture_Warehouse_Storage { get; set; }
        public virtual Fixture_Storage_Outbound_M Fixture_Storage_Outbound_M { get; set; }
        public virtual Fixture_Part Fixture_Part { get; set; }
    }
}
