//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture_Part_Setting_D
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fixture_Part_Setting_D()
        {
            this.Fixture_Part_UseTimes = new HashSet<Fixture_Part_UseTimes>();
        }
    
        public int Fixture_Part_Setting_D_UID { get; set; }
        public int Fixture_Part_Setting_M_UID { get; set; }
        public int Fixture_Part_UID { get; set; }
        public decimal Fixture_Part_Qty { get; set; }
        public decimal Fixture_Part_Life { get; set; }
        public bool Is_Enable { get; set; }
        public int Created_UID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool IsUseTimesManagement { get; set; }
        public Nullable<int> Fixture_Part_Life_UseTimes { get; set; }
    
        public virtual Fixture_Part Fixture_Part { get; set; }
        public virtual Fixture_Part_Setting_M Fixture_Part_Setting_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_UseTimes> Fixture_Part_UseTimes { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
