//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture_Part_UseTimes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fixture_Part_UseTimes()
        {
            this.Fixture_Part_ClearHistory = new HashSet<Fixture_Part_ClearHistory>();
        }
    
        public int Fixture_Part_UseTimes_UID { get; set; }
        public int Fixture_M_UID { get; set; }
        public int Fixture_Part_Setting_D_UID { get; set; }
        public int Fixture_Part_UseTimesCount { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual Fixture_M Fixture_M { get; set; }
        public virtual Fixture_Part_Setting_D Fixture_Part_Setting_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_ClearHistory> Fixture_Part_ClearHistory { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
