//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture_Resume_History
    {
        public int Fixture_Resume_UID { get; set; }
        public int Fixture_M_UID { get; set; }
        public string Data_Source { get; set; }
        public System.DateTime Resume_Date { get; set; }
        public int Source_UID { get; set; }
        public string Source_NO { get; set; }
        public string Resume_Notes { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual Fixture_M Fixture_M { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
