//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture_Part_Order_Schedule
    {
        public int Fixture_Part_Order_Schedule_UID { get; set; }
        public int Fixture_Part_Order_D_UID { get; set; }
        public System.DateTime Estimated_Delivery_Date { get; set; }
        public decimal Estimated_Delivery_Qty { get; set; }
        public int Estimated_Data_Maintainer_UID { get; set; }
        public System.DateTime Estimated_Data_Maintainer_Date { get; set; }
        public Nullable<System.DateTime> Actual_Delivery_Date { get; set; }
        public Nullable<decimal> Actual_Delivery_Qty { get; set; }
        public Nullable<int> Delivery_Data_Maintainer_UID { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public bool Del_Flag { get; set; }
    
        public virtual Fixture_Part_Order_D Fixture_Part_Order_D { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
