//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture_Warehouse_Storage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fixture_Warehouse_Storage()
        {
            this.Fixture_Part_Inventory = new HashSet<Fixture_Part_Inventory>();
            this.Fixture_Storage_InOut_Detail = new HashSet<Fixture_Storage_InOut_Detail>();
            this.Fixture_Storage_Transfer = new HashSet<Fixture_Storage_Transfer>();
            this.Fixture_Storage_Transfer1 = new HashSet<Fixture_Storage_Transfer>();
            this.Fixture_Storage_Inbound = new HashSet<Fixture_Storage_Inbound>();
            this.Fixture_Storage_Outbound_D = new HashSet<Fixture_Storage_Outbound_D>();
            this.Fixture_Storage_Check = new HashSet<Fixture_Storage_Check>();
        }
    
        public int Fixture_Warehouse_Storage_UID { get; set; }
        public int Plant_Organization_UID { get; set; }
        public int BG_Organization_UID { get; set; }
        public Nullable<int> FunPlant_Organization_UID { get; set; }
        public int Fixture_Warehouse_UID { get; set; }
        public string Storage_ID { get; set; }
        public string Rack_ID { get; set; }
        public string Remarks { get; set; }
        public bool Is_Enable { get; set; }
        public int Created_UID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Inventory> Fixture_Part_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_InOut_Detail> Fixture_Storage_InOut_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Transfer> Fixture_Storage_Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Transfer> Fixture_Storage_Transfer1 { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        public virtual System_Organization System_Organization1 { get; set; }
        public virtual System_Organization System_Organization2 { get; set; }
        public virtual Fixture_Warehouse Fixture_Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Inbound> Fixture_Storage_Inbound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Outbound_D> Fixture_Storage_Outbound_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Check> Fixture_Storage_Check { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
