//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture_Part_Demand_Summary_D
    {
        public int Fixture_Part_Demand_Summary_D_UID { get; set; }
        public int Fixture_Part_Demand_Summary_M_UID { get; set; }
        public int Fixture_Part_UID { get; set; }
        public decimal Storage_Qty { get; set; }
        public decimal Total_Gross_Demand { get; set; }
        public decimal Total_User_Adjustments_Qty { get; set; }
        public decimal Total_Actual_Demand { get; set; }
        public decimal Safe_Storage_Qty { get; set; }
        public bool Is_Deleted { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual Fixture_Part_Demand_Summary_M Fixture_Part_Demand_Summary_M { get; set; }
        public virtual Fixture_Part Fixture_Part { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
