//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture_Storage_Transfer
    {
        public int Fixture_Storage_Transfer_UID { get; set; }
        public string Fixture_Storage_Transfer_ID { get; set; }
        public int Fixture_Part_UID { get; set; }
        public int Out_Fixture_Warehouse_Storage_UID { get; set; }
        public int In_Fixture_Warehouse_Storage_UID { get; set; }
        public decimal Transfer_Qty { get; set; }
        public int Applicant_UID { get; set; }
        public System.DateTime Applicant_Date { get; set; }
        public int Status_UID { get; set; }
        public int Approver_UID { get; set; }
        public System.DateTime Approver_Date { get; set; }
    
        public virtual Enumeration Enumeration { get; set; }
        public virtual Fixture_Warehouse_Storage Fixture_Warehouse_Storage { get; set; }
        public virtual Fixture_Warehouse_Storage Fixture_Warehouse_Storage1 { get; set; }
        public virtual Fixture_Part Fixture_Part { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
