//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowChart_IEData
    {
        public Nullable<int> FlowChart_Detail_UID { get; set; }
        public decimal FlowChart_IEData_UID { get; set; }
        public System.DateTime IE_TargetDate { get; set; }
        public Nullable<int> ShiftTimeID { get; set; }
        public Nullable<int> IE_TargetEfficacy { get; set; }
        public Nullable<int> IE_DeptHuman { get; set; }
        public Nullable<int> Modified_UID { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual FlowChart_Detail FlowChart_Detail { get; set; }
        public virtual GL_ShiftTime GL_ShiftTime { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
