//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowChart_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlowChart_Detail()
        {
            this.ExceptionTypeWithFlowchart = new HashSet<ExceptionTypeWithFlowchart>();
            this.ExceptionTypeWithFlowchart1 = new HashSet<ExceptionTypeWithFlowchart>();
            this.FlowChart_PC_MH_Relationship = new HashSet<FlowChart_PC_MH_Relationship>();
            this.OQC_InputMaster_History = new HashSet<OQC_InputMaster_History>();
            this.OQC_InputMaster = new HashSet<OQC_InputMaster>();
            this.PPForQAInterface = new HashSet<PPForQAInterface>();
            this.Product_Rework_Info = new HashSet<Product_Rework_Info>();
            this.Product_Rework_Info1 = new HashSet<Product_Rework_Info>();
            this.Product_Rework_Info_History = new HashSet<Product_Rework_Info_History>();
            this.Product_Rework_Info_History1 = new HashSet<Product_Rework_Info_History>();
            this.QualityAssurance_DistributeRate = new HashSet<QualityAssurance_DistributeRate>();
            this.QualityAssurance_InputMaster = new HashSet<QualityAssurance_InputMaster>();
            this.QualityAssurance_InputMaster_History = new HashSet<QualityAssurance_InputMaster_History>();
            this.FlowChart_MgData = new HashSet<FlowChart_MgData>();
            this.QualityAssurance_MgData = new HashSet<QualityAssurance_MgData>();
            this.MES_StationDataRecord = new HashSet<MES_StationDataRecord>();
            this.ProcessIDTransformConfig = new HashSet<ProcessIDTransformConfig>();
            this.FlowChart_IEData = new HashSet<FlowChart_IEData>();
        }
    
        public int FlowChart_Detail_UID { get; set; }
        public int FlowChart_Master_UID { get; set; }
        public int System_FunPlant_UID { get; set; }
        public int Process_Seq { get; set; }
        public string DRI { get; set; }
        public string Place { get; set; }
        public string Process { get; set; }
        public int Product_Stage { get; set; }
        public string Color { get; set; }
        public string Process_Desc { get; set; }
        public string Material_No { get; set; }
        public int FlowChart_Version { get; set; }
        public string FlowChart_Version_Comment { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public Nullable<int> FatherProcess_UID { get; set; }
        public string IsQAProcess { get; set; }
        public string Rework_Flag { get; set; }
        public int WIP_QTY { get; set; }
        public int Binding_Seq { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string ToWHSOK { get; set; }
        public string ToWHSNG { get; set; }
        public string ItemNo { get; set; }
        public string Edition { get; set; }
        public string FromWHS { get; set; }
        public string RelatedRepairUID { get; set; }
        public bool Location_Flag { get; set; }
        public int Current_WH_QTY { get; set; }
        public int NullWip { get; set; }
        public string Data_Source { get; set; }
        public bool Is_Synchronous { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionTypeWithFlowchart> ExceptionTypeWithFlowchart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionTypeWithFlowchart> ExceptionTypeWithFlowchart1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_PC_MH_Relationship> FlowChart_PC_MH_Relationship { get; set; }
        public virtual System_Function_Plant System_Function_Plant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OQC_InputMaster_History> OQC_InputMaster_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OQC_InputMaster> OQC_InputMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPForQAInterface> PPForQAInterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Rework_Info> Product_Rework_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Rework_Info> Product_Rework_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Rework_Info_History> Product_Rework_Info_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Rework_Info_History> Product_Rework_Info_History1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_DistributeRate> QualityAssurance_DistributeRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_InputMaster> QualityAssurance_InputMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_InputMaster_History> QualityAssurance_InputMaster_History { get; set; }
        public virtual FlowChart_Master FlowChart_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_MgData> FlowChart_MgData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_MgData> QualityAssurance_MgData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MES_StationDataRecord> MES_StationDataRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessIDTransformConfig> ProcessIDTransformConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_IEData> FlowChart_IEData { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
