//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_AssemblyModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GL_AssemblyModel()
        {
            this.GL_AssemblyModelChange = new HashSet<GL_AssemblyModelChange>();
            this.GL_AssemblyModelChange1 = new HashSet<GL_AssemblyModelChange>();
            this.GL_BuildPlan = new HashSet<GL_BuildPlan>();
            this.GL_LineShiftPerf = new HashSet<GL_LineShiftPerf>();
            this.GL_StationShiftPerf = new HashSet<GL_StationShiftPerf>();
            this.GL_StdLineModel = new HashSet<GL_StdLineModel>();
            this.GL_StdLineModelStation = new HashSet<GL_StdLineModelStation>();
            this.GL_StdWIPRoute = new HashSet<GL_StdWIPRoute>();
            this.GL_StdWIPRouteSummary = new HashSet<GL_StdWIPRouteSummary>();
            this.GL_WIPEvent = new HashSet<GL_WIPEvent>();
            this.GL_WIPHourOutput = new HashSet<GL_WIPHourOutput>();
            this.GL_WIPShiftOutput = new HashSet<GL_WIPShiftOutput>();
            this.GL_WIPShiftBatchOutput = new HashSet<GL_WIPShiftBatchOutput>();
        }
    
        public int AssemblyID { get; set; }
        public string AssemblyNumber { get; set; }
        public string AssemblyFamily { get; set; }
        public int CustomerID { get; set; }
        public bool IsEnabled { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_AssemblyModelChange> GL_AssemblyModelChange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_AssemblyModelChange> GL_AssemblyModelChange1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_BuildPlan> GL_BuildPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineShiftPerf> GL_LineShiftPerf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StationShiftPerf> GL_StationShiftPerf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StdLineModel> GL_StdLineModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StdLineModelStation> GL_StdLineModelStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StdWIPRoute> GL_StdWIPRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StdWIPRouteSummary> GL_StdWIPRouteSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPEvent> GL_WIPEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPHourOutput> GL_WIPHourOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPShiftOutput> GL_WIPShiftOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPShiftBatchOutput> GL_WIPShiftBatchOutput { get; set; }
        public virtual System_Project System_Project { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
