//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_BuildPlan
    {
        public int BuildPlanID { get; set; }
        public int CustomerID { get; set; }
        public int LineID { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int PlanOutput { get; set; }
        public Nullable<int> BPSourceID { get; set; }
        public string OutputDate { get; set; }
        public int ShiftTimeID { get; set; }
        public int Created_UID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public Nullable<int> PlanHC { get; set; }
        public Nullable<int> ActualHC { get; set; }
    
        public virtual GL_AssemblyModel GL_AssemblyModel { get; set; }
        public virtual System_Project System_Project { get; set; }
        public virtual GL_Line GL_Line { get; set; }
        public virtual GL_ShiftTime GL_ShiftTime { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
