//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GL_Line()
        {
            this.GL_BuildPlanSource = new HashSet<GL_BuildPlanSource>();
            this.GL_Device = new HashSet<GL_Device>();
            this.GL_BuildPlan = new HashSet<GL_BuildPlan>();
            this.GL_LineShiftPerf = new HashSet<GL_LineShiftPerf>();
            this.GL_StationShiftPerf = new HashSet<GL_StationShiftPerf>();
            this.GL_StdLineModel = new HashSet<GL_StdLineModel>();
            this.GL_StdLineModelStation = new HashSet<GL_StdLineModelStation>();
            this.GL_WIPEvent = new HashSet<GL_WIPEvent>();
            this.GL_WIPHourOutput = new HashSet<GL_WIPHourOutput>();
            this.GL_WIPShiftOutput = new HashSet<GL_WIPShiftOutput>();
            this.GL_WIPShiftBatchOutput = new HashSet<GL_WIPShiftBatchOutput>();
            this.OEE_StationDefectCode = new HashSet<OEE_StationDefectCode>();
            this.OEE_MachineInfo = new HashSet<OEE_MachineInfo>();
            this.GL_LineShiftResposibleUser = new HashSet<GL_LineShiftResposibleUser>();
            this.OEE_DownTimeCode = new HashSet<OEE_DownTimeCode>();
            this.GL_Station = new HashSet<GL_Station>();
            this.GL_LineGroup = new HashSet<GL_LineGroup>();
            this.OEE_ImprovementPlan = new HashSet<OEE_ImprovementPlan>();
            this.GL_ActionTasker = new HashSet<GL_ActionTasker>();
        }
    
        public int LineID { get; set; }
        public int Plant_Organization_UID { get; set; }
        public int BG_Organization_UID { get; set; }
        public Nullable<int> FunPlant_Organization_UID { get; set; }
        public string Phase { get; set; }
        public string LineName { get; set; }
        public string MESLineName { get; set; }
        public int CustomerID { get; set; }
        public int Seq { get; set; }
        public bool IsEnabled { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public decimal CycleTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_BuildPlanSource> GL_BuildPlanSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Device> GL_Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_BuildPlan> GL_BuildPlan { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        public virtual System_Organization System_Organization1 { get; set; }
        public virtual System_Organization System_Organization2 { get; set; }
        public virtual System_Project System_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineShiftPerf> GL_LineShiftPerf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StationShiftPerf> GL_StationShiftPerf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StdLineModel> GL_StdLineModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StdLineModelStation> GL_StdLineModelStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPEvent> GL_WIPEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPHourOutput> GL_WIPHourOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPShiftOutput> GL_WIPShiftOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPShiftBatchOutput> GL_WIPShiftBatchOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDefectCode> OEE_StationDefectCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineInfo> OEE_MachineInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineShiftResposibleUser> GL_LineShiftResposibleUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeCode> OEE_DownTimeCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Station> GL_Station { get; set; }
        public virtual System_Users System_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineGroup> GL_LineGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_ImprovementPlan> OEE_ImprovementPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ActionTasker> GL_ActionTasker { get; set; }
    }
}
