//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_QADetectionPoint
    {
        public int QADetectionPointID { get; set; }
        public int StationID { get; set; }
        public int WIP { get; set; }
        public string ScanIN { get; set; }
        public string ScanOUT { get; set; }
        public string ScanNG { get; set; }
        public string ScanBACK { get; set; }
        public bool IsEnabled { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual GL_Station GL_Station { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
