//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Rest
    {
        public int ShiftTimeID { get; set; }
        public int RestID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public int SEQ { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Time { get; set; }
    
        public virtual GL_ShiftTime GL_ShiftTime { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
