//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_StdWIPRouteSummary
    {
        public int SWRSID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public string WorkCenter { get; set; }
        public string SubWorkCenter { get; set; }
        public string CustomerFamily { get; set; }
        public int GRP { get; set; }
        public string Bottleneck { get; set; }
        public decimal Cycle { get; set; }
        public decimal MLT { get; set; }
        public decimal TCT { get; set; }
        public decimal LBL { get; set; }
        public decimal LBR { get; set; }
        public decimal OBL { get; set; }
        public decimal OBR { get; set; }
        public int HC { get; set; }
        public decimal UPH { get; set; }
        public decimal FixedUPH { get; set; }
        public decimal UPPH { get; set; }
        public decimal SMH { get; set; }
        public decimal FixedSMH { get; set; }
        public int PBs { get; set; }
        public string MapModelName { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual GL_AssemblyModel GL_AssemblyModel { get; set; }
        public virtual System_Project System_Project { get; set; }
    }
}
