//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_StationHistory
    {
        public int StationHistoryID { get; set; }
        public Nullable<int> StationID { get; set; }
        public int Plant_Organization_UID { get; set; }
        public int BG_Organization_UID { get; set; }
        public Nullable<int> FunPlant_Organization_UID { get; set; }
        public string StationName { get; set; }
        public string MESStationName { get; set; }
        public int LineHistoryID { get; set; }
        public bool IsBirth { get; set; }
        public bool IsOutput { get; set; }
        public bool IsTest { get; set; }
        public int Seq { get; set; }
        public string Operation { get; set; }
        public decimal CycleTime { get; set; }
        public bool IsEnabled { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public Nullable<int> Binding_Seq { get; set; }
        public bool IsGoldenLine { get; set; }
        public bool IsOEE { get; set; }
        public bool IsOne { get; set; }
        public bool IsTwo { get; set; }
        public bool IsThree { get; set; }
        public bool IsFour { get; set; }
        public bool IsFive { get; set; }
    
        public virtual GL_LineHistory GL_LineHistory { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        public virtual System_Organization System_Organization1 { get; set; }
        public virtual System_Organization System_Organization2 { get; set; }
    }
}
