//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Station
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GL_Station()
        {
            this.GL_Device = new HashSet<GL_Device>();
            this.GL_GoldenStationCTRecord = new HashSet<GL_GoldenStationCTRecord>();
            this.GL_QADetectionPoint = new HashSet<GL_QADetectionPoint>();
            this.GL_QATargetYield = new HashSet<GL_QATargetYield>();
            this.GL_StationShiftPerf = new HashSet<GL_StationShiftPerf>();
            this.GL_StdLineModelStation = new HashSet<GL_StdLineModelStation>();
            this.GL_WIPEvent = new HashSet<GL_WIPEvent>();
            this.GL_WIPHourOutput = new HashSet<GL_WIPHourOutput>();
            this.GL_WIPShiftOutput = new HashSet<GL_WIPShiftOutput>();
            this.GL_WIPShiftBatchOutput = new HashSet<GL_WIPShiftBatchOutput>();
            this.IPQCQualityReport = new HashSet<IPQCQualityReport>();
            this.IPQCQualityDetial = new HashSet<IPQCQualityDetial>();
            this.OEE_DownTimeCode = new HashSet<OEE_DownTimeCode>();
            this.OEE_MachineInfo = new HashSet<OEE_MachineInfo>();
            this.OEE_StationDefectCode = new HashSet<OEE_StationDefectCode>();
            this.OEE_StationImprovement_Plan = new HashSet<OEE_StationImprovement_Plan>();
            this.OEE_StationDailyDownSum = new HashSet<OEE_StationDailyDownSum>();
            this.OEE_UserStation = new HashSet<OEE_UserStation>();
            this.OEE_MachineDailyDownRecord = new HashSet<OEE_MachineDailyDownRecord>();
            this.OEE_ImprovementPlan = new HashSet<OEE_ImprovementPlan>();
            this.GL_ActionTasker = new HashSet<GL_ActionTasker>();
        }
    
        public int StationID { get; set; }
        public int Plant_Organization_UID { get; set; }
        public int BG_Organization_UID { get; set; }
        public Nullable<int> FunPlant_Organization_UID { get; set; }
        public string StationName { get; set; }
        public int LineID { get; set; }
        public bool IsBirth { get; set; }
        public bool IsOutput { get; set; }
        public bool IsTest { get; set; }
        public int Seq { get; set; }
        public bool IsEnabled { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public decimal CycleTime { get; set; }
        public string MESStationName { get; set; }
        public int Binding_Seq { get; set; }
        public bool IsGoldenLine { get; set; }
        public bool IsOEE { get; set; }
        public bool IsOne { get; set; }
        public bool IsTwo { get; set; }
        public bool IsThree { get; set; }
        public bool IsFour { get; set; }
        public bool IsFive { get; set; }
        public string DashboardTarget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Device> GL_Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_GoldenStationCTRecord> GL_GoldenStationCTRecord { get; set; }
        public virtual GL_Line GL_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_QADetectionPoint> GL_QADetectionPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_QATargetYield> GL_QATargetYield { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        public virtual System_Organization System_Organization1 { get; set; }
        public virtual System_Organization System_Organization2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StationShiftPerf> GL_StationShiftPerf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StdLineModelStation> GL_StdLineModelStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPEvent> GL_WIPEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPHourOutput> GL_WIPHourOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPShiftOutput> GL_WIPShiftOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPShiftBatchOutput> GL_WIPShiftBatchOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPQCQualityReport> IPQCQualityReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPQCQualityDetial> IPQCQualityDetial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeCode> OEE_DownTimeCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineInfo> OEE_MachineInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDefectCode> OEE_StationDefectCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationImprovement_Plan> OEE_StationImprovement_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDailyDownSum> OEE_StationDailyDownSum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_UserStation> OEE_UserStation { get; set; }
        public virtual System_Users System_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineDailyDownRecord> OEE_MachineDailyDownRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_ImprovementPlan> OEE_ImprovementPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ActionTasker> GL_ActionTasker { get; set; }
    }
}
