//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_StdWIPRoute
    {
        public int SWRID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public string WorkCenter { get; set; }
        public string SubWorkCenter { get; set; }
        public string Process { get; set; }
        public int Order { get; set; }
        public string PBO { get; set; }
        public int CalHC { get; set; }
        public decimal StdRouteCT { get; set; }
        public string MapStation { get; set; }
        public bool IsEnabled { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual GL_AssemblyModel GL_AssemblyModel { get; set; }
        public virtual System_Project System_Project { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
