//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_StdLineModel
    {
        public int SLMID { get; set; }
        public int LineID { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public Nullable<decimal> UPH { get; set; }
        public Nullable<decimal> SMH { get; set; }
        public Nullable<decimal> Banlance { get; set; }
        public Nullable<decimal> UPPH { get; set; }
        public Nullable<int> HC { get; set; }
    
        public virtual GL_AssemblyModel GL_AssemblyModel { get; set; }
        public virtual GL_Line GL_Line { get; set; }
    }
}
