//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_WIPEvent
    {
        public int WIPEvent_ID { get; set; }
        public int CustomerID { get; set; }
        public int LineID { get; set; }
        public int StationID { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool IsEnabled { get; set; }
        public int DataSource_ID { get; set; }
    
        public virtual GL_AssemblyModel GL_AssemblyModel { get; set; }
        public virtual GL_DataSource GL_DataSource { get; set; }
        public virtual System_Project System_Project { get; set; }
        public virtual GL_Line GL_Line { get; set; }
        public virtual GL_Station GL_Station { get; set; }
    }
}
