//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPQCQualityDetial
    {
        public int IPQCQualityDetial_UID { get; set; }
        public int StationID { get; set; }
        public int ShiftID { get; set; }
        public System.DateTime ProductDate { get; set; }
        public string TimeInterval { get; set; }
        public int TimeIntervalIndex { get; set; }
        public string NGName { get; set; }
        public int NGNumber { get; set; }
        public string NGType { get; set; }
        public System.DateTime ModifyTime { get; set; }
    
        public virtual GL_ShiftTime GL_ShiftTime { get; set; }
        public virtual GL_Station GL_Station { get; set; }
    }
}
