//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnifeLifeTime
    {
        public int KnifeLifeTime_UID { get; set; }
        public string EQPType { get; set; }
        public string Area { get; set; }
        public string EQPIDID { get; set; }
        public string ToolID { get; set; }
        public string ToolMaterielid { get; set; }
        public string ToolType { get; set; }
        public int LifeStandard { get; set; }
        public int UseToolNumber { get; set; }
        public Nullable<int> LeaveLife { get; set; }
        public Nullable<int> LifeAlarm { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
