//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadSpeedHistory
    {
        public int LoadSpeedUID { get; set; }
        public string eqpid { get; set; }
        public string EQPType { get; set; }
        public string area { get; set; }
        public Nullable<short> Headstock_LoadStandard { get; set; }
        public Nullable<short> Headstock_LoadUpper { get; set; }
        public Nullable<short> Headstock_LoadLower { get; set; }
        public Nullable<short> Headstock_SpeedStandard { get; set; }
        public Nullable<short> Headstock_SpeedUpper { get; set; }
        public Nullable<short> Headstock_SpeedLower { get; set; }
        public Nullable<short> Headstock_Load { get; set; }
        public Nullable<short> Headstock_Speed { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string flag { get; set; }
        public string SpeedState { get; set; }
        public string LoadState { get; set; }
    }
}
