//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine_Yield
    {
        public int Machine_Yield_UID { get; set; }
        public int Machine_Station_UID { get; set; }
        public string Machine_ID { get; set; }
        public Nullable<int> InPut_Qty { get; set; }
        public Nullable<int> NG_Qty { get; set; }
        public Nullable<int> NG_Point_Qty { get; set; }
        public Nullable<System.DateTime> StarTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Yield_Qty { get; set; }
        public Nullable<decimal> Yield { get; set; }
        public Nullable<decimal> NO_Yield { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual Machine_Station Machine_Station { get; set; }
    }
}
