//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Maintenance_Record
    {
        public int Material_Maintenance_Record_UID { get; set; }
        public int Plant_Organization_UID { get; set; }
        public int BG_Organization_UID { get; set; }
        public Nullable<int> FunPlant_Organization_UID { get; set; }
        public int Material_UID { get; set; }
        public string Material_Seq { get; set; }
        public bool Is_Warranty { get; set; }
        public int Submit_UID { get; set; }
        public System.DateTime Submit_Date { get; set; }
        public Nullable<int> Judge_UID { get; set; }
        public Nullable<System.DateTime> Judge_Date { get; set; }
        public string Abnormal { get; set; }
        public System.DateTime Delivery_Date { get; set; }
        public System.DateTime Expected_Return_Date { get; set; }
        public Nullable<int> Acceptance_Staff_UID { get; set; }
        public Nullable<System.DateTime> Acceptance_Date { get; set; }
        public string Acceptance_Results { get; set; }
        public string Vendor { get; set; }
        public string Maintenance_Items { get; set; }
        public Nullable<decimal> Maintenance_Fees { get; set; }
        public Nullable<int> Maintenance_Days { get; set; }
        public string Notes { get; set; }
        public int Status_UID { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public Nullable<int> Return_UID { get; set; }
        public Nullable<System.DateTime> Return_Time { get; set; }
        public Nullable<int> Modified_UID { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Material_Info Material_Info { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        public virtual System_Organization System_Organization1 { get; set; }
        public virtual System_Organization System_Organization2 { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
        public virtual System_Users System_Users2 { get; set; }
        public virtual System_Users System_Users3 { get; set; }
        public virtual System_Users System_Users4 { get; set; }
    }
}
