//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Demand_Summary
    {
        public int Material_Demand_Summary_UID { get; set; }
        public int BG_Organization_UID { get; set; }
        public int FunPlant_Organization_UID { get; set; }
        public int Material_UID { get; set; }
        public decimal NormalDemand_Qty { get; set; }
        public decimal SparepartsDemand_Qty { get; set; }
        public decimal Repair_Demand_Qty { get; set; }
        public decimal Be_Purchase_Qty { get; set; }
        public System.DateTime Calculation_Date { get; set; }
        public System.DateTime Demand_Date { get; set; }
        public int Applicant_UID { get; set; }
        public System.DateTime Applicant_Date { get; set; }
        public int Status_UID { get; set; }
        public int Approver_UID { get; set; }
        public System.DateTime Approver_Date { get; set; }
    
        public virtual Enumeration Enumeration { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        public virtual System_Organization System_Organization1 { get; set; }
        public virtual Material_Info Material_Info { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
