//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material_Info()
        {
            this.EQP_Material = new HashSet<EQP_Material>();
            this.EQP_Material1 = new HashSet<EQP_Material>();
            this.Material_Demand_Summary = new HashSet<Material_Demand_Summary>();
            this.Material_Inventory = new HashSet<Material_Inventory>();
            this.Material_Normal_Demand = new HashSet<Material_Normal_Demand>();
            this.Material_Reason = new HashSet<Material_Reason>();
            this.Material_Repair_Demand = new HashSet<Material_Repair_Demand>();
            this.Material_Spareparts_Demand = new HashSet<Material_Spareparts_Demand>();
            this.Meterial_UpdateInfo = new HashSet<Meterial_UpdateInfo>();
            this.Storage_Check = new HashSet<Storage_Check>();
            this.Storage_Inbound = new HashSet<Storage_Inbound>();
            this.Storage_InOut_Detail = new HashSet<Storage_InOut_Detail>();
            this.Storage_Outbound_D = new HashSet<Storage_Outbound_D>();
            this.Storage_Transfer = new HashSet<Storage_Transfer>();
            this.Material_Maintenance_Record = new HashSet<Material_Maintenance_Record>();
        }
    
        public int Material_Uid { get; set; }
        public string Material_Id { get; set; }
        public string Material_Name { get; set; }
        public string Material_Types { get; set; }
        public string Assembly_Name { get; set; }
        public string Classification { get; set; }
        public Nullable<int> Warehouse_Storage_UID { get; set; }
        public string Cost_Center { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<int> Delivery_Date { get; set; }
        public Nullable<int> Maintenance_Cycle { get; set; }
        public Nullable<int> Material_Life { get; set; }
        public Nullable<int> Requisitions_Cycle { get; set; }
        public Nullable<int> Sign_days { get; set; }
        public Nullable<decimal> Daily_Consumption { get; set; }
        public Nullable<int> Monthly_Consumption { get; set; }
        public Nullable<bool> IsRework { get; set; }
        public Nullable<bool> Is_Enable { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public Nullable<int> Organization_UID { get; set; }
        public Nullable<decimal> Last_Qty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQP_Material> EQP_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQP_Material> EQP_Material1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Demand_Summary> Material_Demand_Summary { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        public virtual Warehouse_Storage Warehouse_Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Inventory> Material_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Normal_Demand> Material_Normal_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Reason> Material_Reason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Repair_Demand> Material_Repair_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Spareparts_Demand> Material_Spareparts_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meterial_UpdateInfo> Meterial_UpdateInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Check> Storage_Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Inbound> Storage_Inbound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_InOut_Detail> Storage_InOut_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Outbound_D> Storage_Outbound_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Transfer> Storage_Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Maintenance_Record> Material_Maintenance_Record { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
