//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_PIS_SyncFailedRecord
    {
        public int MES_PIS_SyncFailedRecord_UID { get; set; }
        public string SyncType { get; set; }
        public string SyncName { get; set; }
        public System.DateTime SyncTime { get; set; }
        public string SyncRequest { get; set; }
        public string SyncResult { get; set; }
        public bool Is_ManuallySuccess { get; set; }
        public int FailedNumber { get; set; }
        public int OperateID { get; set; }
        public System.DateTime OperateTime { get; set; }
    }
}
