//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meterial_UpdateInfo
    {
        public int PartsUpdate_Uid { get; set; }
        public int Material_Uid { get; set; }
        public System.DateTime Update_DateTime { get; set; }
        public int Update_No { get; set; }
        public int EQP_Uid { get; set; }
        public Nullable<decimal> Update_Cost { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public Nullable<int> Modified_UID { get; set; }
        public int Repair_Uid { get; set; }
        public Nullable<int> Modified_EQPUser_Uid { get; set; }
        public string Reason_Analysis { get; set; }
    
        public virtual Material_Info Material_Info { get; set; }
        public virtual Equipment_Info Equipment_Info { get; set; }
        public virtual EQPRepair_Info EQPRepair_Info { get; set; }
    }
}
