//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelLineHR
    {
        public int ModelLineHR_UID { get; set; }
        public string Station { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> ShouldCome { get; set; }
        public Nullable<int> ActualCome { get; set; }
        public Nullable<int> VacationLeave { get; set; }
        public Nullable<int> PersonalLeave { get; set; }
        public Nullable<int> SickLeave { get; set; }
        public Nullable<int> AbsentLeave { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
    }
}
