//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int UID { get; set; }
        public string Notice_Content { get; set; }
        public string Scope { get; set; }
        public string State { get; set; }
        public string Color { get; set; }
        public int Creator_UID { get; set; }
        public System.DateTime Start_Time { get; set; }
        public System.DateTime End_Time { get; set; }
        public System.DateTime Creat_Time { get; set; }
        public Nullable<int> RepeatTime { get; set; }
    }
}
