//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEE_StationImprovement_Plan
    {
        public int OEE_StationDefectCode_UID { get; set; }
        public int Plant_Organization_UID { get; set; }
        public int BG_Organization_UID { get; set; }
        public Nullable<int> FunPlant_Organization_UID { get; set; }
        public int Years { get; set; }
        public int WeekOfYear { get; set; }
        public int StationID { get; set; }
        public int Top_Class { get; set; }
        public string Problem_Description { get; set; }
        public string Analysis { get; set; }
        public string PA { get; set; }
        public string Responsible { get; set; }
        public System.DateTime Commit_Date { get; set; }
        public System.DateTime Completion_Date { get; set; }
        public bool Is_Enable { get; set; }
        public int Modify_UID { get; set; }
        public System.DateTime Modify_Date { get; set; }
    
        public virtual GL_Station GL_Station { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
