//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEE_MachineDailyDownRecord
    {
        public int OEE_MachineDailyDownRecord_UID { get; set; }
        public int Plant_Organization_UID { get; set; }
        public int BG_Organization_UID { get; set; }
        public Nullable<int> FunPlant_Organization_UID { get; set; }
        public int StationID { get; set; }
        public int OEE_MachineInfo_UID { get; set; }
        public int OEE_DownTimeCode_UID { get; set; }
        public System.DateTime DownDate { get; set; }
        public int ShiftTimeID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTIme { get; set; }
        public int DownTime { get; set; }
        public Nullable<bool> Is_Calculate { get; set; }
    
        public virtual GL_ShiftTime GL_ShiftTime { get; set; }
        public virtual GL_Station GL_Station { get; set; }
        public virtual OEE_DownTimeCode OEE_DownTimeCode { get; set; }
        public virtual OEE_MachineInfo OEE_MachineInfo { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        public virtual System_Organization System_Organization1 { get; set; }
        public virtual System_Organization System_Organization2 { get; set; }
    }
}
