//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEE_MachineStatus
    {
        public int OEE_MachineStatus_UID { get; set; }
        public int OEE_MachineInfo_UID { get; set; }
        public System.DateTime Product_Date { get; set; }
        public int ShiftTimeID { get; set; }
        public int StatusID { get; set; }
        public int StatusDuration { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual GL_ShiftTime GL_ShiftTime { get; set; }
        public virtual OEE_MachineInfo OEE_MachineInfo { get; set; }
    }
}
