//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OQC_InputMaster_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OQC_InputMaster_History()
        {
            this.OQC_InputDetail_History = new HashSet<OQC_InputDetail_History>();
        }
    
        public Nullable<int> FlowChart_Detail_UID { get; set; }
        public int OQCMater_UID { get; set; }
        public string Time_interval { get; set; }
        public System.DateTime ProductDate { get; set; }
        public string MaterialType { get; set; }
        public string Color { get; set; }
        public Nullable<int> Input { get; set; }
        public Nullable<int> GoodParts_Qty { get; set; }
        public Nullable<int> NGParts_Qty { get; set; }
        public Nullable<int> Rework { get; set; }
        public Nullable<int> ProductLineRework { get; set; }
        public Nullable<int> ReworkQtyFromAssemble { get; set; }
        public Nullable<int> RepairNG_Qty { get; set; }
        public Nullable<int> NG_Qty { get; set; }
        public Nullable<decimal> RepairNG_Yield { get; set; }
        public Nullable<decimal> NG_Yield { get; set; }
        public Nullable<decimal> FirstYieldRate { get; set; }
        public Nullable<decimal> SecondYieldRate { get; set; }
        public Nullable<int> Storage_Qty { get; set; }
        public Nullable<int> WaitStorage_Qty { get; set; }
        public Nullable<int> WIP { get; set; }
        public int Creator_UID { get; set; }
        public System.DateTime Create_date { get; set; }
        public System.DateTime Modified_date { get; set; }
        public Nullable<int> Modifier_UID { get; set; }
        public Nullable<int> Project_UID { get; set; }
        public Nullable<int> ReworkQtyFromOQC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OQC_InputDetail_History> OQC_InputDetail_History { get; set; }
        public virtual FlowChart_Detail FlowChart_Detail { get; set; }
        public virtual System_Project System_Project { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
