//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrigCoordMonHistory
    {
        public int OrigCoordMonUID { get; set; }
        public string EQPType { get; set; }
        public string EQPID { get; set; }
        public string Area { get; set; }
        public string Coordinate { get; set; }
        public Nullable<short> Original { get; set; }
        public Nullable<short> Max { get; set; }
        public Nullable<short> Min { get; set; }
        public Nullable<short> Actual { get; set; }
        public Nullable<short> ErrorQTY { get; set; }
        public string State { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
