//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPForQAInterface
    {
        public int Interface_UID { get; set; }
        public int FlowChart_Detail_UID { get; set; }
        public int Input_Qty { get; set; }
        public int NG_Qty { get; set; }
        public System.DateTime Product_Date { get; set; }
        public string Time_Interval { get; set; }
        public string Color { get; set; }
        public string MaterielType { get; set; }
        public bool QAUsedFlag { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public int ReWorkQty { get; set; }
        public int Good_Qty { get; set; }
    
        public virtual FlowChart_Detail FlowChart_Detail { get; set; }
    }
}
