//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessIDTransformConfig
    {
        public int ProcessTransformConfig_UID { get; set; }
        public int Binding_Seq { get; set; }
        public int PIS_ProcessID { get; set; }
        public string PIS_ProcessName { get; set; }
        public string MES_NgID { get; set; }
        public string MES_PickingID { get; set; }
        public string MES_ReworkID { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string ReMark { get; set; }
        public string Color { get; set; }
        public string MES_GoodProductID { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsSyncNG { get; set; }
    
        public virtual FlowChart_Detail FlowChart_Detail { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
