//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Rework_Info_History
    {
        public int Rework_UID { get; set; }
        public int Product_UID { get; set; }
        public int FlowChart_Detail_UID { get; set; }
        public int Opposite_Detail_UID { get; set; }
        public Nullable<int> Opposite_QTY { get; set; }
        public System.DateTime Product_Date { get; set; }
        public string Time_Interval { get; set; }
        public bool Is_Match { get; set; }
        public string Rework_Type { get; set; }
        public string Rework_Flag { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual FlowChart_Detail FlowChart_Detail { get; set; }
        public virtual FlowChart_Detail FlowChart_Detail1 { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
