//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QEboardSum
    {
        public int QEboadSum_UID { get; set; }
        public int FlowChartMaster_UID { get; set; }
        public string Project { get; set; }
        public string Part_Types { get; set; }
        public string Product_Date { get; set; }
        public string Time_Interval { get; set; }
        public int Process_Seq { get; set; }
        public string Process { get; set; }
        public int OneCheck_QTY { get; set; }
        public int OneCheck_OK { get; set; }
        public int NGReuse { get; set; }
        public int NGReject { get; set; }
        public double OneTargetYield { get; set; }
        public double OneYield { get; set; }
        public int RepairOK { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public double SecondTargetYield { get; set; }
        public double SecondYield { get; set; }
    }
}
