//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityAssurance_MgData
    {
        public int QualityAssurance_MgData_UID { get; set; }
        public decimal FirstRejectionRate { get; set; }
        public decimal SecondRejectionRate { get; set; }
        public System.DateTime ProductDate { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public Nullable<int> Modified_UID { get; set; }
        public Nullable<int> FlowChart_Master_UID { get; set; }
        public System.DateTime Create_Date { get; set; }
        public Nullable<int> Creator_UID { get; set; }
        public Nullable<int> Process_seq { get; set; }
        public string Process { get; set; }
        public Nullable<int> FlowChart_Detail_UID { get; set; }
    
        public virtual FlowChart_Master FlowChart_Master { get; set; }
        public virtual FlowChart_Detail FlowChart_Detail { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
