//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityAssurance_InputDetail
    {
        public Nullable<int> QualityAssurance_InputMaster_UID { get; set; }
        public int QualityAssurance_InputDetail_UID { get; set; }
        public int ExceptionType_UID { get; set; }
        public Nullable<int> Repair_Qty { get; set; }
        public Nullable<int> SepcialAccept_Qty { get; set; }
        public Nullable<int> RepairNG_Qty { get; set; }
        public Nullable<int> NG_Qty { get; set; }
        public int Creator_UID { get; set; }
        public System.DateTime Create_Date { get; set; }
        public Nullable<int> Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sys_Account_UID { get; set; }
        public Nullable<int> Displace_Qty { get; set; }
        public Nullable<int> System_FunPlant_UID { get; set; }
    
        public virtual QualityAssurance_InputMaster QualityAssurance_InputMaster { get; set; }
        public virtual System_Function_Plant System_Function_Plant { get; set; }
        public virtual QualityAssurance_ExceptionType QualityAssurance_ExceptionType { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
