//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityAssurance_DataChangeLog
    {
        public int Log_UID { get; set; }
        public Nullable<int> QualityAssurance_InputDetail_UID { get; set; }
        public Nullable<int> QualityAssurance_InputMaster_UID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> LastRepair_Qty { get; set; }
        public Nullable<int> LastSepcialAccept_Qty { get; set; }
        public Nullable<int> LastNG_Qty { get; set; }
        public Nullable<int> LastRepairNG_Qty { get; set; }
        public Nullable<int> NewRepair_Qty { get; set; }
        public Nullable<int> NewSepcialAccept_Qty { get; set; }
        public Nullable<int> NewNG_Qty { get; set; }
        public Nullable<int> NewRepairNG_Qty { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string ModifiedReason { get; set; }
        public Nullable<int> LastDisplace_Qty { get; set; }
        public Nullable<int> NewDisplace_Qty { get; set; }
    
        public virtual System_Users System_Users { get; set; }
    }
}
