//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityAssurance_DistributeRate
    {
        public System.Guid QualityAssurance_DistributeRate_UID { get; set; }
        public Nullable<int> FlowChart_Master_UID { get; set; }
        public Nullable<int> FlowChart_Detail_UID { get; set; }
        public Nullable<int> System_FunPlant_UID { get; set; }
        public Nullable<int> ExceptionType_UID { get; set; }
        public Nullable<decimal> RejectionRate { get; set; }
        public Nullable<decimal> Surface_Rate { get; set; }
        public string RateType { get; set; }
        public Nullable<decimal> Anode_Rate { get; set; }
        public Nullable<decimal> OQC_Rate { get; set; }
        public Nullable<decimal> CNC_Rate { get; set; }
        public Nullable<decimal> Assemble_Rate { get; set; }
        public Nullable<System.DateTime> ProductDate { get; set; }
        public string Color { get; set; }
        public string MaterialType { get; set; }
    
        public virtual FlowChart_Master FlowChart_Master { get; set; }
        public virtual System_Function_Plant System_Function_Plant { get; set; }
        public virtual FlowChart_Detail FlowChart_Detail { get; set; }
        public virtual QualityAssurance_ExceptionType QualityAssurance_ExceptionType { get; set; }
    }
}
