//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_Flowchart_Detail_ME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RP_Flowchart_Detail_ME()
        {
            this.Actual_Production_Manpower = new HashSet<Actual_Production_Manpower>();
            this.Predict_Production_Information = new HashSet<Predict_Production_Information>();
            this.RP_Flowchart_Detail_ME_Equipment = new HashSet<RP_Flowchart_Detail_ME_Equipment>();
            this.RP_Manpower_Demand = new HashSet<RP_Manpower_Demand>();
            this.RP_Flowchart_Detail_IE = new HashSet<RP_Flowchart_Detail_IE>();
        }
    
        public int RP_Flowchart_Detail_ME_UID { get; set; }
        public int RP_Flowchart_Master_UID { get; set; }
        public int FunPlant_Organization_UID { get; set; }
        public int Process_Seq { get; set; }
        public string Process_Station { get; set; }
        public string Process { get; set; }
        public string Process_Desc { get; set; }
        public string Processing_Equipment { get; set; }
        public string Automation_Equipment { get; set; }
        public string Processing_Fixtures { get; set; }
        public string Auxiliary_Equipment { get; set; }
        public Nullable<decimal> Equipment_CT { get; set; }
        public Nullable<decimal> Setup_Time { get; set; }
        public Nullable<decimal> Total_Cycletime { get; set; }
        public decimal ME_Estimate_Yield { get; set; }
        public Nullable<decimal> Manpower_Ratio { get; set; }
        public decimal Capacity_ByHour { get; set; }
        public decimal Capacity_ByDay { get; set; }
        public Nullable<decimal> Equipment_RequstQty { get; set; }
        public Nullable<int> Manpower_2Shift { get; set; }
        public int Created_UID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actual_Production_Manpower> Actual_Production_Manpower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predict_Production_Information> Predict_Production_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Detail_ME_Equipment> RP_Flowchart_Detail_ME_Equipment { get; set; }
        public virtual RP_Flowchart_Master RP_Flowchart_Master { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Manpower_Demand> RP_Manpower_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Detail_IE> RP_Flowchart_Detail_IE { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
