//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage_Outbound_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Storage_Outbound_M()
        {
            this.Storage_Outbound_D = new HashSet<Storage_Outbound_D>();
        }
    
        public int Storage_Outbound_M_UID { get; set; }
        public int Storage_Outbound_Type_UID { get; set; }
        public string Storage_Outbound_ID { get; set; }
        public Nullable<int> Repair_Uid { get; set; }
        public Nullable<int> Outbound_Account_UID { get; set; }
        public int Applicant_UID { get; set; }
        public System.DateTime Applicant_Date { get; set; }
        public int Status_UID { get; set; }
        public string Desc { get; set; }
        public int Approver_UID { get; set; }
        public System.DateTime Approver_Date { get; set; }
    
        public virtual Enumeration Enumeration { get; set; }
        public virtual Enumeration Enumeration1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Outbound_D> Storage_Outbound_D { get; set; }
        public virtual EQP_UserTable EQP_UserTable { get; set; }
        public virtual EQPRepair_Info EQPRepair_Info { get; set; }
        public virtual System_Users System_Users { get; set; }
        public virtual System_Users System_Users1 { get; set; }
    }
}
