//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage_Outbound_D
    {
        public int Storage_Outbound_D_UID { get; set; }
        public int Storage_Outbound_M_UID { get; set; }
        public int Material_UID { get; set; }
        public int Warehouse_Storage_UID { get; set; }
        public int PartType_UID { get; set; }
        public decimal Outbound_Qty { get; set; }
        public Nullable<decimal> Outbound_Price { get; set; }
        public string Desc { get; set; }
    
        public virtual Enumeration Enumeration { get; set; }
        public virtual Storage_Outbound_M Storage_Outbound_M { get; set; }
        public virtual Warehouse_Storage Warehouse_Storage { get; set; }
        public virtual Material_Info Material_Info { get; set; }
    }
}
