//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Function
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_Function()
        {
            this.System_FunctionSub = new HashSet<System_FunctionSub>();
            this.System_Role_Function = new HashSet<System_Role_Function>();
            this.System_Module = new HashSet<System_Module>();
            this.System_Schedule = new HashSet<System_Schedule>();
            this.APP_USER_FAVORITES_FUNCTION = new HashSet<APP_USER_FAVORITES_FUNCTION>();
        }
    
        public int Function_UID { get; set; }
        public Nullable<int> Parent_Function_UID { get; set; }
        public string Function_ID { get; set; }
        public string Function_Name { get; set; }
        public string Function_Desc { get; set; }
        public int Order_Index { get; set; }
        public string Icon_ClassName { get; set; }
        public string URL { get; set; }
        public string Mobile_URL { get; set; }
        public bool Is_Show { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_FunctionSub> System_FunctionSub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Role_Function> System_Role_Function { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Module> System_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Schedule> System_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_USER_FAVORITES_FUNCTION> APP_USER_FAVORITES_FUNCTION { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
