//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Role_FunctionSub_SystemAdmin
    {
        public int System_Role_FunctionSub_UID { get; set; }
        public int System_Role_Function_UID { get; set; }
        public int System_FunctionSub_UID { get; set; }
        public bool Sub_Flag { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    }
}
