//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_Project()
        {
            this.FlowChart_Master = new HashSet<FlowChart_Master>();
            this.GL_AssemblyModel = new HashSet<GL_AssemblyModel>();
            this.GL_AssemblyModelChange = new HashSet<GL_AssemblyModelChange>();
            this.GL_BuildPlanLineMapping = new HashSet<GL_BuildPlanLineMapping>();
            this.GL_CustomerShiftPerf = new HashSet<GL_CustomerShiftPerf>();
            this.GL_CustomerTarget = new HashSet<GL_CustomerTarget>();
            this.GL_Device = new HashSet<GL_Device>();
            this.GL_LineHistory = new HashSet<GL_LineHistory>();
            this.GL_LineShiftPerf = new HashSet<GL_LineShiftPerf>();
            this.GL_MealTime = new HashSet<GL_MealTime>();
            this.GL_MESSource = new HashSet<GL_MESSource>();
            this.GL_StationShiftPerf = new HashSet<GL_StationShiftPerf>();
            this.GL_StdWIPRoute = new HashSet<GL_StdWIPRoute>();
            this.GL_StdWIPRouteSummary = new HashSet<GL_StdWIPRouteSummary>();
            this.GL_WIPEvent = new HashSet<GL_WIPEvent>();
            this.GL_WIPHourOutput = new HashSet<GL_WIPHourOutput>();
            this.GL_WIPShiftBatchOutput = new HashSet<GL_WIPShiftBatchOutput>();
            this.GL_WIPShiftOutput = new HashSet<GL_WIPShiftOutput>();
            this.OQC_InputMaster = new HashSet<OQC_InputMaster>();
            this.OQC_InputMaster_History = new HashSet<OQC_InputMaster_History>();
            this.Production_Line = new HashSet<Production_Line>();
            this.Project_Users_Group = new HashSet<Project_Users_Group>();
            this.RP_Demand_Calculation_Record = new HashSet<RP_Demand_Calculation_Record>();
            this.RP_Flowchart_Master = new HashSet<RP_Flowchart_Master>();
            this.GL_BuildPlan = new HashSet<GL_BuildPlan>();
            this.WorkStation = new HashSet<WorkStation>();
            this.GL_Line = new HashSet<GL_Line>();
            this.OEE_StationDefectCode = new HashSet<OEE_StationDefectCode>();
            this.Fixture_M = new HashSet<Fixture_M>();
            this.CNCMachine = new HashSet<CNCMachine>();
            this.OEE_MachineInfo = new HashSet<OEE_MachineInfo>();
            this.OEE_DownTimeCode = new HashSet<OEE_DownTimeCode>();
            this.GL_LineGroup = new HashSet<GL_LineGroup>();
            this.Exception_Project = new HashSet<Exception_Project>();
            this.OEE_ImprovementPlan = new HashSet<OEE_ImprovementPlan>();
            this.Exception_Record = new HashSet<Exception_Record>();
            this.GL_ActionTasker = new HashSet<GL_ActionTasker>();
        }
    
        public int Project_UID { get; set; }
        public string Project_Code { get; set; }
        public int BU_D_UID { get; set; }
        public string Project_Name { get; set; }
        public string Product_Phase { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string OP_TYPES { get; set; }
        public int Organization_UID { get; set; }
        public string Project_Type { get; set; }
        public string MESProject_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_Master> FlowChart_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_AssemblyModel> GL_AssemblyModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_AssemblyModelChange> GL_AssemblyModelChange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_BuildPlanLineMapping> GL_BuildPlanLineMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_CustomerShiftPerf> GL_CustomerShiftPerf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_CustomerTarget> GL_CustomerTarget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Device> GL_Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineHistory> GL_LineHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineShiftPerf> GL_LineShiftPerf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MealTime> GL_MealTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MESSource> GL_MESSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StationShiftPerf> GL_StationShiftPerf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StdWIPRoute> GL_StdWIPRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StdWIPRouteSummary> GL_StdWIPRouteSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPEvent> GL_WIPEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPHourOutput> GL_WIPHourOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPShiftBatchOutput> GL_WIPShiftBatchOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_WIPShiftOutput> GL_WIPShiftOutput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OQC_InputMaster> OQC_InputMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OQC_InputMaster_History> OQC_InputMaster_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production_Line> Production_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Users_Group> Project_Users_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Demand_Calculation_Record> RP_Demand_Calculation_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Master> RP_Flowchart_Master { get; set; }
        public virtual System_BU_D System_BU_D { get; set; }
        public virtual System_BU_D System_BU_D1 { get; set; }
        public virtual System_Organization System_Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_BuildPlan> GL_BuildPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkStation> WorkStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Line> GL_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDefectCode> OEE_StationDefectCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_M> Fixture_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNCMachine> CNCMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineInfo> OEE_MachineInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeCode> OEE_DownTimeCode { get; set; }
        public virtual System_Users System_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineGroup> GL_LineGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Project> Exception_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_ImprovementPlan> OEE_ImprovementPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Record> Exception_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ActionTasker> GL_ActionTasker { get; set; }
    }
}
