//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_Users()
        {
            this.Actual_Production_Equipment_Qty = new HashSet<Actual_Production_Equipment_Qty>();
            this.Actual_Production_Equipment_Qty1 = new HashSet<Actual_Production_Equipment_Qty>();
            this.Actual_Production_Manpower = new HashSet<Actual_Production_Manpower>();
            this.Actual_Production_Manpower1 = new HashSet<Actual_Production_Manpower>();
            this.APP_USER_FAVORITES_FUNCTION = new HashSet<APP_USER_FAVORITES_FUNCTION>();
            this.CNCMachine = new HashSet<CNCMachine>();
            this.Current_Manpower = new HashSet<Current_Manpower>();
            this.Current_Manpower1 = new HashSet<Current_Manpower>();
            this.DefectCode_Group = new HashSet<DefectCode_Group>();
            this.DefectCode_Group1 = new HashSet<DefectCode_Group>();
            this.DefectCode_RepairSolution = new HashSet<DefectCode_RepairSolution>();
            this.DefectCode_RepairSolution1 = new HashSet<DefectCode_RepairSolution>();
            this.DemissionRateAndWorkSchedule = new HashSet<DemissionRateAndWorkSchedule>();
            this.DemissionRateAndWorkSchedule1 = new HashSet<DemissionRateAndWorkSchedule>();
            this.EQP_Forecast_PowerOn = new HashSet<EQP_Forecast_PowerOn>();
            this.EQP_Material = new HashSet<EQP_Material>();
            this.EQP_PowerOn = new HashSet<EQP_PowerOn>();
            this.EQP_Type = new HashSet<EQP_Type>();
            this.EQP_UserTable = new HashSet<EQP_UserTable>();
            this.EQPRepair_Info = new HashSet<EQPRepair_Info>();
            this.Equipment_Info = new HashSet<Equipment_Info>();
            this.Exception_Code = new HashSet<Exception_Code>();
            this.Exception_Code1 = new HashSet<Exception_Code>();
            this.Exception_Dept = new HashSet<Exception_Dept>();
            this.Exception_Dept1 = new HashSet<Exception_Dept>();
            this.Exception_Reply = new HashSet<Exception_Reply>();
            this.Exception_Resume = new HashSet<Exception_Resume>();
            this.Exception_Time = new HashSet<Exception_Time>();
            this.Exception_Time1 = new HashSet<Exception_Time>();
            this.ExceptionTypeWithFlowchart = new HashSet<ExceptionTypeWithFlowchart>();
            this.Fixture_DefectCode = new HashSet<Fixture_DefectCode>();
            this.Fixture_DefectCode1 = new HashSet<Fixture_DefectCode>();
            this.Fixture_M = new HashSet<Fixture_M>();
            this.Fixture_M1 = new HashSet<Fixture_M>();
            this.Fixture_Machine = new HashSet<Fixture_Machine>();
            this.Fixture_Machine1 = new HashSet<Fixture_Machine>();
            this.Fixture_Maintenance_Profile = new HashSet<Fixture_Maintenance_Profile>();
            this.Fixture_Maintenance_Profile1 = new HashSet<Fixture_Maintenance_Profile>();
            this.Fixture_Maintenance_Record = new HashSet<Fixture_Maintenance_Record>();
            this.Fixture_Maintenance_Record1 = new HashSet<Fixture_Maintenance_Record>();
            this.Fixture_Maintenance_Record2 = new HashSet<Fixture_Maintenance_Record>();
            this.Fixture_Maintenance_Record_History = new HashSet<Fixture_Maintenance_Record_History>();
            this.Fixture_Maintenance_Record_History1 = new HashSet<Fixture_Maintenance_Record_History>();
            this.Fixture_Maintenance_Record_History2 = new HashSet<Fixture_Maintenance_Record_History>();
            this.Fixture_Part = new HashSet<Fixture_Part>();
            this.Fixture_Part1 = new HashSet<Fixture_Part>();
            this.Fixture_Part_ClearHistory = new HashSet<Fixture_Part_ClearHistory>();
            this.Fixture_Part_Demand_D = new HashSet<Fixture_Part_Demand_D>();
            this.Fixture_Part_Demand_M = new HashSet<Fixture_Part_Demand_M>();
            this.Fixture_Part_Demand_M1 = new HashSet<Fixture_Part_Demand_M>();
            this.Fixture_Part_Demand_Summary_D = new HashSet<Fixture_Part_Demand_Summary_D>();
            this.Fixture_Part_Demand_Summary_M = new HashSet<Fixture_Part_Demand_Summary_M>();
            this.Fixture_Part_Demand_Summary_M1 = new HashSet<Fixture_Part_Demand_Summary_M>();
            this.Fixture_Part_Inventory = new HashSet<Fixture_Part_Inventory>();
            this.Fixture_Part_Order_D = new HashSet<Fixture_Part_Order_D>();
            this.Fixture_Part_Order_D1 = new HashSet<Fixture_Part_Order_D>();
            this.Fixture_Part_Order_M = new HashSet<Fixture_Part_Order_M>();
            this.Fixture_Part_Order_M1 = new HashSet<Fixture_Part_Order_M>();
            this.Fixture_Part_Order_Schedule = new HashSet<Fixture_Part_Order_Schedule>();
            this.Fixture_Part_Order_Schedule1 = new HashSet<Fixture_Part_Order_Schedule>();
            this.Fixture_Part_Setting_D = new HashSet<Fixture_Part_Setting_D>();
            this.Fixture_Part_Setting_D1 = new HashSet<Fixture_Part_Setting_D>();
            this.Fixture_Part_Setting_M = new HashSet<Fixture_Part_Setting_M>();
            this.Fixture_Part_Setting_M1 = new HashSet<Fixture_Part_Setting_M>();
            this.Fixture_Part_UseTimes = new HashSet<Fixture_Part_UseTimes>();
            this.Fixture_Repair_D = new HashSet<Fixture_Repair_D>();
            this.Fixture_Repair_D1 = new HashSet<Fixture_Repair_D>();
            this.Fixture_Repair_D2 = new HashSet<Fixture_Repair_D>();
            this.Fixture_Repair_D_Defect = new HashSet<Fixture_Repair_D_Defect>();
            this.Fixture_Repair_D_Defect1 = new HashSet<Fixture_Repair_D_Defect>();
            this.Fixture_Repair_M = new HashSet<Fixture_Repair_M>();
            this.Fixture_Repair_M1 = new HashSet<Fixture_Repair_M>();
            this.Fixture_Repair_M2 = new HashSet<Fixture_Repair_M>();
            this.Fixture_RepairSolution = new HashSet<Fixture_RepairSolution>();
            this.Fixture_RepairSolution1 = new HashSet<Fixture_RepairSolution>();
            this.Fixture_Resume = new HashSet<Fixture_Resume>();
            this.Fixture_Resume_History = new HashSet<Fixture_Resume_History>();
            this.Fixture_Return_D = new HashSet<Fixture_Return_D>();
            this.Fixture_Return_M = new HashSet<Fixture_Return_M>();
            this.Fixture_Return_M1 = new HashSet<Fixture_Return_M>();
            this.Fixture_Storage_Check = new HashSet<Fixture_Storage_Check>();
            this.Fixture_Storage_Check1 = new HashSet<Fixture_Storage_Check>();
            this.Fixture_Storage_Inbound = new HashSet<Fixture_Storage_Inbound>();
            this.Fixture_Storage_Inbound1 = new HashSet<Fixture_Storage_Inbound>();
            this.Fixture_Storage_InOut_Detail = new HashSet<Fixture_Storage_InOut_Detail>();
            this.Fixture_Storage_Outbound_M = new HashSet<Fixture_Storage_Outbound_M>();
            this.Fixture_Storage_Outbound_M1 = new HashSet<Fixture_Storage_Outbound_M>();
            this.Fixture_Storage_Outbound_M2 = new HashSet<Fixture_Storage_Outbound_M>();
            this.Fixture_Storage_Transfer = new HashSet<Fixture_Storage_Transfer>();
            this.Fixture_Storage_Transfer1 = new HashSet<Fixture_Storage_Transfer>();
            this.Fixture_Totake_D = new HashSet<Fixture_Totake_D>();
            this.Fixture_Totake_D1 = new HashSet<Fixture_Totake_D>();
            this.Fixture_Totake_M = new HashSet<Fixture_Totake_M>();
            this.Fixture_Totake_M1 = new HashSet<Fixture_Totake_M>();
            this.Fixture_Totake_M2 = new HashSet<Fixture_Totake_M>();
            this.Fixture_User_Workshop = new HashSet<Fixture_User_Workshop>();
            this.Fixture_User_Workshop1 = new HashSet<Fixture_User_Workshop>();
            this.Fixture_User_Workshop2 = new HashSet<Fixture_User_Workshop>();
            this.Fixture_Warehouse = new HashSet<Fixture_Warehouse>();
            this.Fixture_Warehouse1 = new HashSet<Fixture_Warehouse>();
            this.Fixture_Warehouse_Storage = new HashSet<Fixture_Warehouse_Storage>();
            this.Fixture_Warehouse_Storage1 = new HashSet<Fixture_Warehouse_Storage>();
            this.FixtureDefectCode_Setting = new HashSet<FixtureDefectCode_Setting>();
            this.FixtureDefectCode_Setting1 = new HashSet<FixtureDefectCode_Setting>();
            this.FlowChart_Detail = new HashSet<FlowChart_Detail>();
            this.FlowChart_IEData = new HashSet<FlowChart_IEData>();
            this.FlowChart_Master = new HashSet<FlowChart_Master>();
            this.FlowChart_Master1 = new HashSet<FlowChart_Master>();
            this.FlowChart_MgData = new HashSet<FlowChart_MgData>();
            this.FlowChart_PC_MH_Relationship = new HashSet<FlowChart_PC_MH_Relationship>();
            this.FlowChart_PC_MH_Relationship1 = new HashSet<FlowChart_PC_MH_Relationship>();
            this.GL_AssemblyModel = new HashSet<GL_AssemblyModel>();
            this.GL_AssemblyModelChange = new HashSet<GL_AssemblyModelChange>();
            this.GL_BuildPlanLineMapping = new HashSet<GL_BuildPlanLineMapping>();
            this.GL_BuildPlanSource = new HashSet<GL_BuildPlanSource>();
            this.GL_CustomerTarget = new HashSet<GL_CustomerTarget>();
            this.GL_Device = new HashSet<GL_Device>();
            this.GL_Line = new HashSet<GL_Line>();
            this.GL_LineHistory = new HashSet<GL_LineHistory>();
            this.GL_LineShiftResposibleUser = new HashSet<GL_LineShiftResposibleUser>();
            this.GL_LineShiftResposibleUser1 = new HashSet<GL_LineShiftResposibleUser>();
            this.GL_MealTime = new HashSet<GL_MealTime>();
            this.GL_MESSource = new HashSet<GL_MESSource>();
            this.GL_QADetectionPoint = new HashSet<GL_QADetectionPoint>();
            this.GL_QATargetYield = new HashSet<GL_QATargetYield>();
            this.GL_Rest = new HashSet<GL_Rest>();
            this.GL_ShiftTime = new HashSet<GL_ShiftTime>();
            this.GL_Station = new HashSet<GL_Station>();
            this.GL_StdWIPRoute = new HashSet<GL_StdWIPRoute>();
            this.Machine_Customer = new HashSet<Machine_Customer>();
            this.Machine_Customer1 = new HashSet<Machine_Customer>();
            this.Machine_Station = new HashSet<Machine_Station>();
            this.Machine_Station1 = new HashSet<Machine_Station>();
            this.Maintenance_Plan = new HashSet<Maintenance_Plan>();
            this.Maintenance_Plan1 = new HashSet<Maintenance_Plan>();
            this.Material_Demand_Summary = new HashSet<Material_Demand_Summary>();
            this.Material_Demand_Summary1 = new HashSet<Material_Demand_Summary>();
            this.Material_Info = new HashSet<Material_Info>();
            this.Material_Info1 = new HashSet<Material_Info>();
            this.Material_Inventory = new HashSet<Material_Inventory>();
            this.Material_Maintenance_Record = new HashSet<Material_Maintenance_Record>();
            this.Material_Maintenance_Record1 = new HashSet<Material_Maintenance_Record>();
            this.Material_Maintenance_Record2 = new HashSet<Material_Maintenance_Record>();
            this.Material_Maintenance_Record3 = new HashSet<Material_Maintenance_Record>();
            this.Material_Maintenance_Record4 = new HashSet<Material_Maintenance_Record>();
            this.Material_Normal_Demand = new HashSet<Material_Normal_Demand>();
            this.Material_Normal_Demand1 = new HashSet<Material_Normal_Demand>();
            this.Material_Reason = new HashSet<Material_Reason>();
            this.Material_Repair_Demand = new HashSet<Material_Repair_Demand>();
            this.Material_Repair_Demand1 = new HashSet<Material_Repair_Demand>();
            this.Material_Spareparts_Demand = new HashSet<Material_Spareparts_Demand>();
            this.Material_Spareparts_Demand1 = new HashSet<Material_Spareparts_Demand>();
            this.OEE_DefectCodeDailyNum = new HashSet<OEE_DefectCodeDailyNum>();
            this.OEE_DownTimeCode = new HashSet<OEE_DownTimeCode>();
            this.OEE_DownTimeType = new HashSet<OEE_DownTimeType>();
            this.OEE_EveryDayDFcodeMissing = new HashSet<OEE_EveryDayDFcodeMissing>();
            this.OEE_EveryDayMachineDTCode = new HashSet<OEE_EveryDayMachineDTCode>();
            this.OEE_MachineInfo = new HashSet<OEE_MachineInfo>();
            this.OEE_StationDefectCode = new HashSet<OEE_StationDefectCode>();
            this.OEE_StationImprovement_Plan = new HashSet<OEE_StationImprovement_Plan>();
            this.OEE_UserStation = new HashSet<OEE_UserStation>();
            this.OEE_UserStation1 = new HashSet<OEE_UserStation>();
            this.OQC_InputDetail = new HashSet<OQC_InputDetail>();
            this.OQC_InputDetail_History = new HashSet<OQC_InputDetail_History>();
            this.OQC_InputMaster = new HashSet<OQC_InputMaster>();
            this.OQC_InputMaster_History = new HashSet<OQC_InputMaster_History>();
            this.PlayBoard_PlayTime = new HashSet<PlayBoard_PlayTime>();
            this.PlayBoard_Setting = new HashSet<PlayBoard_Setting>();
            this.PlayBoard_Setting1 = new HashSet<PlayBoard_Setting>();
            this.PlayBoard_Setting2 = new HashSet<PlayBoard_Setting>();
            this.PlayBoard_View = new HashSet<PlayBoard_View>();
            this.PlayBoard_View1 = new HashSet<PlayBoard_View>();
            this.Predict_Production_Information = new HashSet<Predict_Production_Information>();
            this.Predict_Production_Information1 = new HashSet<Predict_Production_Information>();
            this.Process_Info = new HashSet<Process_Info>();
            this.Process_Info1 = new HashSet<Process_Info>();
            this.ProcessIDTransformConfig = new HashSet<ProcessIDTransformConfig>();
            this.Product_Input = new HashSet<Product_Input>();
            this.Product_Input_History = new HashSet<Product_Input_History>();
            this.Product_Rework_Info = new HashSet<Product_Rework_Info>();
            this.Product_Rework_Info_History = new HashSet<Product_Rework_Info_History>();
            this.Production_Line = new HashSet<Production_Line>();
            this.Production_Line1 = new HashSet<Production_Line>();
            this.Project_Users_Group = new HashSet<Project_Users_Group>();
            this.Project_Users_Group1 = new HashSet<Project_Users_Group>();
            this.QualityAssurance_DataChangeLog = new HashSet<QualityAssurance_DataChangeLog>();
            this.QualityAssurance_ExceptionType = new HashSet<QualityAssurance_ExceptionType>();
            this.QualityAssurance_ExceptionType_Temp = new HashSet<QualityAssurance_ExceptionType_Temp>();
            this.QualityAssurance_InputDetail = new HashSet<QualityAssurance_InputDetail>();
            this.QualityAssurance_InputDetail1 = new HashSet<QualityAssurance_InputDetail>();
            this.QualityAssurance_InputDetail_History = new HashSet<QualityAssurance_InputDetail_History>();
            this.QualityAssurance_InputMaster = new HashSet<QualityAssurance_InputMaster>();
            this.QualityAssurance_InputMaster1 = new HashSet<QualityAssurance_InputMaster>();
            this.QualityAssurance_MgData = new HashSet<QualityAssurance_MgData>();
            this.Repair_Location = new HashSet<Repair_Location>();
            this.Repair_Location1 = new HashSet<Repair_Location>();
            this.RP_Demand_Calculation_Record = new HashSet<RP_Demand_Calculation_Record>();
            this.RP_Equipment_Demand = new HashSet<RP_Equipment_Demand>();
            this.RP_Flowchart_Detail_IE = new HashSet<RP_Flowchart_Detail_IE>();
            this.RP_Flowchart_Detail_IE1 = new HashSet<RP_Flowchart_Detail_IE>();
            this.RP_Flowchart_Detail_ME = new HashSet<RP_Flowchart_Detail_ME>();
            this.RP_Flowchart_Detail_ME1 = new HashSet<RP_Flowchart_Detail_ME>();
            this.RP_Flowchart_Detail_ME_Equipment = new HashSet<RP_Flowchart_Detail_ME_Equipment>();
            this.RP_Flowchart_Detail_ME_Equipment1 = new HashSet<RP_Flowchart_Detail_ME_Equipment>();
            this.RP_Flowchart_Master = new HashSet<RP_Flowchart_Master>();
            this.RP_Flowchart_Master1 = new HashSet<RP_Flowchart_Master>();
            this.RP_Manpower_Demand = new HashSet<RP_Manpower_Demand>();
            this.Storage_Check = new HashSet<Storage_Check>();
            this.Storage_Check1 = new HashSet<Storage_Check>();
            this.Storage_Inbound = new HashSet<Storage_Inbound>();
            this.Storage_Inbound1 = new HashSet<Storage_Inbound>();
            this.Storage_InOut_Detail = new HashSet<Storage_InOut_Detail>();
            this.Storage_Outbound_M = new HashSet<Storage_Outbound_M>();
            this.Storage_Outbound_M1 = new HashSet<Storage_Outbound_M>();
            this.Storage_Transfer = new HashSet<Storage_Transfer>();
            this.Storage_Transfer1 = new HashSet<Storage_Transfer>();
            this.System_BU_D = new HashSet<System_BU_D>();
            this.System_BU_D1 = new HashSet<System_BU_D>();
            this.System_BU_M = new HashSet<System_BU_M>();
            this.System_Email_Attachment = new HashSet<System_Email_Attachment>();
            this.System_Email_Delivery = new HashSet<System_Email_Delivery>();
            this.System_Email_Delivery1 = new HashSet<System_Email_Delivery>();
            this.System_Email_Delivery2 = new HashSet<System_Email_Delivery>();
            this.System_Email_M = new HashSet<System_Email_M>();
            this.System_Function = new HashSet<System_Function>();
            this.System_Function_Plant = new HashSet<System_Function_Plant>();
            this.System_FunctionSub = new HashSet<System_FunctionSub>();
            this.System_Language = new HashSet<System_Language>();
            this.System_LocaleStringResource = new HashSet<System_LocaleStringResource>();
            this.System_LocalizedProperty = new HashSet<System_LocalizedProperty>();
            this.System_Module = new HashSet<System_Module>();
            this.System_Module1 = new HashSet<System_Module>();
            this.System_Organization = new HashSet<System_Organization>();
            this.System_OrganizationBOM = new HashSet<System_OrganizationBOM>();
            this.System_OrganizationBOM1 = new HashSet<System_OrganizationBOM>();
            this.System_Plant = new HashSet<System_Plant>();
            this.System_Project = new HashSet<System_Project>();
            this.System_Role = new HashSet<System_Role>();
            this.System_Role1 = new HashSet<System_Role>();
            this.System_Role_Function = new HashSet<System_Role_Function>();
            this.System_Role_Function1 = new HashSet<System_Role_Function>();
            this.System_Role_FunctionSub = new HashSet<System_Role_FunctionSub>();
            this.System_Schedule = new HashSet<System_Schedule>();
            this.System_Schedule1 = new HashSet<System_Schedule>();
            this.System_Seq = new HashSet<System_Seq>();
            this.System_Seq1 = new HashSet<System_Seq>();
            this.System_User_Business_Group = new HashSet<System_User_Business_Group>();
            this.System_User_Business_Group1 = new HashSet<System_User_Business_Group>();
            this.System_User_Business_Group2 = new HashSet<System_User_Business_Group>();
            this.System_User_FunPlant = new HashSet<System_User_FunPlant>();
            this.System_User_FunPlant1 = new HashSet<System_User_FunPlant>();
            this.System_User_Plant = new HashSet<System_User_Plant>();
            this.System_User_Plant1 = new HashSet<System_User_Plant>();
            this.System_User_Plant2 = new HashSet<System_User_Plant>();
            this.System_User_Role = new HashSet<System_User_Role>();
            this.System_User_Role1 = new HashSet<System_User_Role>();
            this.System_User_View = new HashSet<System_User_View>();
            this.System_User_View1 = new HashSet<System_User_View>();
            this.System_UserOrg = new HashSet<System_UserOrg>();
            this.System_UserOrg1 = new HashSet<System_UserOrg>();
            this.GL_BuildPlan = new HashSet<GL_BuildPlan>();
            this.GL_BuildPlan1 = new HashSet<GL_BuildPlan>();
            this.System_View_Column = new HashSet<System_View_Column>();
            this.Vendor_Info = new HashSet<Vendor_Info>();
            this.Vendor_Info1 = new HashSet<Vendor_Info>();
            this.Warehouse = new HashSet<Warehouse>();
            this.Warehouse_Storage = new HashSet<Warehouse_Storage>();
            this.WIP_Change_History = new HashSet<WIP_Change_History>();
            this.Workshop = new HashSet<Workshop>();
            this.Workshop1 = new HashSet<Workshop>();
            this.WorkStation = new HashSet<WorkStation>();
            this.WorkStation1 = new HashSet<WorkStation>();
            this.Exception_Email = new HashSet<Exception_Email>();
            this.Exception_Email1 = new HashSet<Exception_Email>();
            this.OEE_ImprovementPlan = new HashSet<OEE_ImprovementPlan>();
            this.OEE_ImprovementPlan1 = new HashSet<OEE_ImprovementPlan>();
            this.OEE_MeetingTypeInfo = new HashSet<OEE_MeetingTypeInfo>();
            this.OEE_MetricInfo = new HashSet<OEE_MetricInfo>();
            this.Exception_Record = new HashSet<Exception_Record>();
            this.Exception_Record1 = new HashSet<Exception_Record>();
            this.GL_MeetingTypeInfo = new HashSet<GL_MeetingTypeInfo>();
            this.GL_MetricInfo = new HashSet<GL_MetricInfo>();
            this.GL_ActionTasker = new HashSet<GL_ActionTasker>();
            this.GL_ActionTasker1 = new HashSet<GL_ActionTasker>();
        }
    
        public int Account_UID { get; set; }
        public string User_NTID { get; set; }
        public string User_Name { get; set; }
        public bool Enable_Flag { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public int System_Language_UID { get; set; }
        public string LoginToken { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public bool MH_Flag { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> EnableEmpIdLogin { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeePassword { get; set; }
        public string Building { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actual_Production_Equipment_Qty> Actual_Production_Equipment_Qty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actual_Production_Equipment_Qty> Actual_Production_Equipment_Qty1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actual_Production_Manpower> Actual_Production_Manpower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actual_Production_Manpower> Actual_Production_Manpower1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APP_USER_FAVORITES_FUNCTION> APP_USER_FAVORITES_FUNCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNCMachine> CNCMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Current_Manpower> Current_Manpower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Current_Manpower> Current_Manpower1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectCode_Group> DefectCode_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectCode_Group> DefectCode_Group1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectCode_RepairSolution> DefectCode_RepairSolution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectCode_RepairSolution> DefectCode_RepairSolution1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemissionRateAndWorkSchedule> DemissionRateAndWorkSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemissionRateAndWorkSchedule> DemissionRateAndWorkSchedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQP_Forecast_PowerOn> EQP_Forecast_PowerOn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQP_Material> EQP_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQP_PowerOn> EQP_PowerOn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQP_Type> EQP_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQP_UserTable> EQP_UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQPRepair_Info> EQPRepair_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Info> Equipment_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Code> Exception_Code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Code> Exception_Code1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Dept> Exception_Dept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Dept> Exception_Dept1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Reply> Exception_Reply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Resume> Exception_Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Time> Exception_Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Time> Exception_Time1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionTypeWithFlowchart> ExceptionTypeWithFlowchart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_DefectCode> Fixture_DefectCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_DefectCode> Fixture_DefectCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_M> Fixture_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_M> Fixture_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Machine> Fixture_Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Machine> Fixture_Machine1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Profile> Fixture_Maintenance_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Profile> Fixture_Maintenance_Profile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Record> Fixture_Maintenance_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Record> Fixture_Maintenance_Record1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Record> Fixture_Maintenance_Record2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Record_History> Fixture_Maintenance_Record_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Record_History> Fixture_Maintenance_Record_History1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Record_History> Fixture_Maintenance_Record_History2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part> Fixture_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part> Fixture_Part1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_ClearHistory> Fixture_Part_ClearHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_D> Fixture_Part_Demand_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_M> Fixture_Part_Demand_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_M> Fixture_Part_Demand_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_Summary_D> Fixture_Part_Demand_Summary_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_Summary_M> Fixture_Part_Demand_Summary_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_Summary_M> Fixture_Part_Demand_Summary_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Inventory> Fixture_Part_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Order_D> Fixture_Part_Order_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Order_D> Fixture_Part_Order_D1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Order_M> Fixture_Part_Order_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Order_M> Fixture_Part_Order_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Order_Schedule> Fixture_Part_Order_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Order_Schedule> Fixture_Part_Order_Schedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Setting_D> Fixture_Part_Setting_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Setting_D> Fixture_Part_Setting_D1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Setting_M> Fixture_Part_Setting_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Setting_M> Fixture_Part_Setting_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_UseTimes> Fixture_Part_UseTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_D> Fixture_Repair_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_D> Fixture_Repair_D1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_D> Fixture_Repair_D2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_D_Defect> Fixture_Repair_D_Defect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_D_Defect> Fixture_Repair_D_Defect1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_M> Fixture_Repair_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_M> Fixture_Repair_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_M> Fixture_Repair_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_RepairSolution> Fixture_RepairSolution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_RepairSolution> Fixture_RepairSolution1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Resume> Fixture_Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Resume_History> Fixture_Resume_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Return_D> Fixture_Return_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Return_M> Fixture_Return_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Return_M> Fixture_Return_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Check> Fixture_Storage_Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Check> Fixture_Storage_Check1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Inbound> Fixture_Storage_Inbound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Inbound> Fixture_Storage_Inbound1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_InOut_Detail> Fixture_Storage_InOut_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Outbound_M> Fixture_Storage_Outbound_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Outbound_M> Fixture_Storage_Outbound_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Outbound_M> Fixture_Storage_Outbound_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Transfer> Fixture_Storage_Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Storage_Transfer> Fixture_Storage_Transfer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Totake_D> Fixture_Totake_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Totake_D> Fixture_Totake_D1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Totake_M> Fixture_Totake_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Totake_M> Fixture_Totake_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Totake_M> Fixture_Totake_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_User_Workshop> Fixture_User_Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_User_Workshop> Fixture_User_Workshop1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_User_Workshop> Fixture_User_Workshop2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Warehouse> Fixture_Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Warehouse> Fixture_Warehouse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Warehouse_Storage> Fixture_Warehouse_Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Warehouse_Storage> Fixture_Warehouse_Storage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixtureDefectCode_Setting> FixtureDefectCode_Setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixtureDefectCode_Setting> FixtureDefectCode_Setting1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_Detail> FlowChart_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_IEData> FlowChart_IEData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_Master> FlowChart_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_Master> FlowChart_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_MgData> FlowChart_MgData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_PC_MH_Relationship> FlowChart_PC_MH_Relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_PC_MH_Relationship> FlowChart_PC_MH_Relationship1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_AssemblyModel> GL_AssemblyModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_AssemblyModelChange> GL_AssemblyModelChange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_BuildPlanLineMapping> GL_BuildPlanLineMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_BuildPlanSource> GL_BuildPlanSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_CustomerTarget> GL_CustomerTarget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Device> GL_Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Line> GL_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineHistory> GL_LineHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineShiftResposibleUser> GL_LineShiftResposibleUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineShiftResposibleUser> GL_LineShiftResposibleUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MealTime> GL_MealTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MESSource> GL_MESSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_QADetectionPoint> GL_QADetectionPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_QATargetYield> GL_QATargetYield { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Rest> GL_Rest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ShiftTime> GL_ShiftTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Station> GL_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StdWIPRoute> GL_StdWIPRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Customer> Machine_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Customer> Machine_Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Station> Machine_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Station> Machine_Station1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Plan> Maintenance_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Plan> Maintenance_Plan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Demand_Summary> Material_Demand_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Demand_Summary> Material_Demand_Summary1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Info> Material_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Info> Material_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Inventory> Material_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Maintenance_Record> Material_Maintenance_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Maintenance_Record> Material_Maintenance_Record1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Maintenance_Record> Material_Maintenance_Record2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Maintenance_Record> Material_Maintenance_Record3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Maintenance_Record> Material_Maintenance_Record4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Normal_Demand> Material_Normal_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Normal_Demand> Material_Normal_Demand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Reason> Material_Reason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Repair_Demand> Material_Repair_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Repair_Demand> Material_Repair_Demand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Spareparts_Demand> Material_Spareparts_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Spareparts_Demand> Material_Spareparts_Demand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DefectCodeDailyNum> OEE_DefectCodeDailyNum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeCode> OEE_DownTimeCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeType> OEE_DownTimeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_EveryDayDFcodeMissing> OEE_EveryDayDFcodeMissing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_EveryDayMachineDTCode> OEE_EveryDayMachineDTCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineInfo> OEE_MachineInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDefectCode> OEE_StationDefectCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationImprovement_Plan> OEE_StationImprovement_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_UserStation> OEE_UserStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_UserStation> OEE_UserStation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OQC_InputDetail> OQC_InputDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OQC_InputDetail_History> OQC_InputDetail_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OQC_InputMaster> OQC_InputMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OQC_InputMaster_History> OQC_InputMaster_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayBoard_PlayTime> PlayBoard_PlayTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayBoard_Setting> PlayBoard_Setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayBoard_Setting> PlayBoard_Setting1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayBoard_Setting> PlayBoard_Setting2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayBoard_View> PlayBoard_View { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayBoard_View> PlayBoard_View1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predict_Production_Information> Predict_Production_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predict_Production_Information> Predict_Production_Information1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Process_Info> Process_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Process_Info> Process_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessIDTransformConfig> ProcessIDTransformConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Input> Product_Input { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Input_History> Product_Input_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Rework_Info> Product_Rework_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Rework_Info_History> Product_Rework_Info_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production_Line> Production_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production_Line> Production_Line1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Users_Group> Project_Users_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Users_Group> Project_Users_Group1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_DataChangeLog> QualityAssurance_DataChangeLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_ExceptionType> QualityAssurance_ExceptionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_ExceptionType_Temp> QualityAssurance_ExceptionType_Temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_InputDetail> QualityAssurance_InputDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_InputDetail> QualityAssurance_InputDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_InputDetail_History> QualityAssurance_InputDetail_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_InputMaster> QualityAssurance_InputMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_InputMaster> QualityAssurance_InputMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityAssurance_MgData> QualityAssurance_MgData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair_Location> Repair_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair_Location> Repair_Location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Demand_Calculation_Record> RP_Demand_Calculation_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Equipment_Demand> RP_Equipment_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Detail_IE> RP_Flowchart_Detail_IE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Detail_IE> RP_Flowchart_Detail_IE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Detail_ME> RP_Flowchart_Detail_ME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Detail_ME> RP_Flowchart_Detail_ME1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Detail_ME_Equipment> RP_Flowchart_Detail_ME_Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Detail_ME_Equipment> RP_Flowchart_Detail_ME_Equipment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Master> RP_Flowchart_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Master> RP_Flowchart_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Manpower_Demand> RP_Manpower_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Check> Storage_Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Check> Storage_Check1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Inbound> Storage_Inbound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Inbound> Storage_Inbound1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_InOut_Detail> Storage_InOut_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Outbound_M> Storage_Outbound_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Outbound_M> Storage_Outbound_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Transfer> Storage_Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage_Transfer> Storage_Transfer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_BU_D> System_BU_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_BU_D> System_BU_D1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_BU_M> System_BU_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Email_Attachment> System_Email_Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Email_Delivery> System_Email_Delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Email_Delivery> System_Email_Delivery1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Email_Delivery> System_Email_Delivery2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Email_M> System_Email_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Function> System_Function { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Function_Plant> System_Function_Plant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_FunctionSub> System_FunctionSub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Language> System_Language { get; set; }
        public virtual System_Language System_Language1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_LocaleStringResource> System_LocaleStringResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_LocalizedProperty> System_LocalizedProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Module> System_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Module> System_Module1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Organization> System_Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_OrganizationBOM> System_OrganizationBOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_OrganizationBOM> System_OrganizationBOM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Plant> System_Plant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Project> System_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Role> System_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Role> System_Role1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Role_Function> System_Role_Function { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Role_Function> System_Role_Function1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Role_FunctionSub> System_Role_FunctionSub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Schedule> System_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Schedule> System_Schedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Seq> System_Seq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Seq> System_Seq1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_Business_Group> System_User_Business_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_Business_Group> System_User_Business_Group1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_Business_Group> System_User_Business_Group2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_FunPlant> System_User_FunPlant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_FunPlant> System_User_FunPlant1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_Plant> System_User_Plant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_Plant> System_User_Plant1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_Plant> System_User_Plant2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_Role> System_User_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_Role> System_User_Role1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_View> System_User_View { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_View> System_User_View1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_UserOrg> System_UserOrg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_UserOrg> System_UserOrg1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_BuildPlan> GL_BuildPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_BuildPlan> GL_BuildPlan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_View_Column> System_View_Column { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Info> Vendor_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Info> Vendor_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse_Storage> Warehouse_Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIP_Change_History> WIP_Change_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workshop> Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workshop> Workshop1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkStation> WorkStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkStation> WorkStation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Email> Exception_Email { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Email> Exception_Email1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_ImprovementPlan> OEE_ImprovementPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_ImprovementPlan> OEE_ImprovementPlan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MeetingTypeInfo> OEE_MeetingTypeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MetricInfo> OEE_MetricInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Record> Exception_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exception_Record> Exception_Record1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MeetingTypeInfo> GL_MeetingTypeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MetricInfo> GL_MetricInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ActionTasker> GL_ActionTasker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ActionTasker> GL_ActionTasker1 { get; set; }
    }
}
