//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Email_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_Email_M()
        {
            this.System_Email_Attachment = new HashSet<System_Email_Attachment>();
        }
    
        public int System_Email_M_UID { get; set; }
        public int System_Schedule_UID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Email_From { get; set; }
        public string Email_To { get; set; }
        public string Email_To_UIDs { get; set; }
        public string Email_CC { get; set; }
        public string Email_CC_UIDs { get; set; }
        public string Email_BCC { get; set; }
        public string Email_BCC_UIDs { get; set; }
        public Nullable<System.DateTime> Reservation_Date { get; set; }
        public Nullable<bool> Is_Send { get; set; }
        public Nullable<System.DateTime> Send_Time { get; set; }
        public int Email_Type { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Email_Attachment> System_Email_Attachment { get; set; }
        public virtual System_Schedule System_Schedule { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
