//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_BU_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_BU_M()
        {
            this.System_User_Business_Group = new HashSet<System_User_Business_Group>();
            this.System_BU_D = new HashSet<System_BU_D>();
        }
    
        public int BU_M_UID { get; set; }
        public string BU_ID { get; set; }
        public string BU_Name { get; set; }
        public string BUManager_Name { get; set; }
        public string BUManager_Tel { get; set; }
        public string BUManager_Email { get; set; }
        public System.DateTime Begin_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_Business_Group> System_User_Business_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_BU_D> System_BU_D { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
