//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_Organization()
        {
            this.EQP_Type = new HashSet<EQP_Type>();
            this.EQP_Type1 = new HashSet<EQP_Type>();
            this.FlowChart_Master = new HashSet<FlowChart_Master>();
            this.Material_Demand_Summary = new HashSet<Material_Demand_Summary>();
            this.Material_Demand_Summary1 = new HashSet<Material_Demand_Summary>();
            this.Material_Repair_Demand = new HashSet<Material_Repair_Demand>();
            this.Material_Repair_Demand1 = new HashSet<Material_Repair_Demand>();
            this.Material_Spareparts_Demand = new HashSet<Material_Spareparts_Demand>();
            this.Material_Spareparts_Demand1 = new HashSet<Material_Spareparts_Demand>();
            this.System_Function_Plant = new HashSet<System_Function_Plant>();
            this.System_Function_Plant1 = new HashSet<System_Function_Plant>();
            this.System_OrganizationBOM = new HashSet<System_OrganizationBOM>();
            this.System_OrganizationBOM1 = new HashSet<System_OrganizationBOM>();
            this.System_UserOrg = new HashSet<System_UserOrg>();
            this.Warehouses = new HashSet<Warehouse>();
            this.Warehouses1 = new HashSet<Warehouse>();
            this.System_UserOrg1 = new HashSet<System_UserOrg>();
            this.System_UserOrg2 = new HashSet<System_UserOrg>();
            this.System_UserOrg3 = new HashSet<System_UserOrg>();
            this.System_UserOrg4 = new HashSet<System_UserOrg>();
            this.Material_Normal_Demand = new HashSet<Material_Normal_Demand>();
            this.Material_Normal_Demand1 = new HashSet<Material_Normal_Demand>();
            this.DefectCode_Group = new HashSet<DefectCode_Group>();
            this.DefectCode_Group1 = new HashSet<DefectCode_Group>();
            this.DefectCode_Group2 = new HashSet<DefectCode_Group>();
            this.DefectCode_RepairSolution = new HashSet<DefectCode_RepairSolution>();
            this.DefectCode_RepairSolution1 = new HashSet<DefectCode_RepairSolution>();
            this.DefectCode_RepairSolution2 = new HashSet<DefectCode_RepairSolution>();
            this.Fixture_DefectCode = new HashSet<Fixture_DefectCode>();
            this.Fixture_DefectCode1 = new HashSet<Fixture_DefectCode>();
            this.Fixture_DefectCode2 = new HashSet<Fixture_DefectCode>();
            this.Fixture_Maintenance_Profile = new HashSet<Fixture_Maintenance_Profile>();
            this.Fixture_Maintenance_Profile1 = new HashSet<Fixture_Maintenance_Profile>();
            this.Fixture_Maintenance_Profile2 = new HashSet<Fixture_Maintenance_Profile>();
            this.Fixture_RepairSolution = new HashSet<Fixture_RepairSolution>();
            this.Fixture_RepairSolution1 = new HashSet<Fixture_RepairSolution>();
            this.Fixture_RepairSolution2 = new HashSet<Fixture_RepairSolution>();
            this.FixtureDefectCode_Setting = new HashSet<FixtureDefectCode_Setting>();
            this.FixtureDefectCode_Setting1 = new HashSet<FixtureDefectCode_Setting>();
            this.FixtureDefectCode_Setting2 = new HashSet<FixtureDefectCode_Setting>();
            this.Process_Info = new HashSet<Process_Info>();
            this.Process_Info1 = new HashSet<Process_Info>();
            this.Process_Info2 = new HashSet<Process_Info>();
            this.Production_Line = new HashSet<Production_Line>();
            this.Production_Line1 = new HashSet<Production_Line>();
            this.Production_Line2 = new HashSet<Production_Line>();
            this.Repair_Location = new HashSet<Repair_Location>();
            this.Repair_Location1 = new HashSet<Repair_Location>();
            this.Repair_Location2 = new HashSet<Repair_Location>();
            this.Vendor_Info = new HashSet<Vendor_Info>();
            this.Vendor_Info1 = new HashSet<Vendor_Info>();
            this.Workshop = new HashSet<Workshop>();
            this.Workshop1 = new HashSet<Workshop>();
            this.Workshop2 = new HashSet<Workshop>();
            this.WorkStation = new HashSet<WorkStation>();
            this.WorkStation1 = new HashSet<WorkStation>();
            this.WorkStation2 = new HashSet<WorkStation>();
            this.Maintenance_Plan = new HashSet<Maintenance_Plan>();
            this.Maintenance_Plan1 = new HashSet<Maintenance_Plan>();
            this.Maintenance_Plan2 = new HashSet<Maintenance_Plan>();
            this.Fixture_Repair_M = new HashSet<Fixture_Repair_M>();
            this.Fixture_Repair_M1 = new HashSet<Fixture_Repair_M>();
            this.Fixture_Repair_M2 = new HashSet<Fixture_Repair_M>();
            this.Fixture_Totake_M = new HashSet<Fixture_Totake_M>();
            this.Fixture_Totake_M1 = new HashSet<Fixture_Totake_M>();
            this.Fixture_Totake_M2 = new HashSet<Fixture_Totake_M>();
            this.Fixture_Warehouse_Storage = new HashSet<Fixture_Warehouse_Storage>();
            this.Fixture_Warehouse_Storage1 = new HashSet<Fixture_Warehouse_Storage>();
            this.Fixture_Warehouse_Storage2 = new HashSet<Fixture_Warehouse_Storage>();
            this.System_Module = new HashSet<System_Module>();
            this.System_Email_Delivery = new HashSet<System_Email_Delivery>();
            this.System_Email_Delivery1 = new HashSet<System_Email_Delivery>();
            this.Fixture_Warehouse = new HashSet<Fixture_Warehouse>();
            this.Fixture_Warehouse1 = new HashSet<Fixture_Warehouse>();
            this.Fixture_Warehouse2 = new HashSet<Fixture_Warehouse>();
            this.System_Schedule = new HashSet<System_Schedule>();
            this.Fixture_Part_Demand_M = new HashSet<Fixture_Part_Demand_M>();
            this.Fixture_Part_Demand_M1 = new HashSet<Fixture_Part_Demand_M>();
            this.Fixture_Part_Demand_M2 = new HashSet<Fixture_Part_Demand_M>();
            this.Fixture_Part_Demand_Summary_M = new HashSet<Fixture_Part_Demand_Summary_M>();
            this.Fixture_Part_Demand_Summary_M1 = new HashSet<Fixture_Part_Demand_Summary_M>();
            this.Fixture_Part_Demand_Summary_M2 = new HashSet<Fixture_Part_Demand_Summary_M>();
            this.EQP_UserTable = new HashSet<EQP_UserTable>();
            this.Material_Info = new HashSet<Material_Info>();
            this.Material_Maintenance_Record = new HashSet<Material_Maintenance_Record>();
            this.Material_Maintenance_Record1 = new HashSet<Material_Maintenance_Record>();
            this.Material_Maintenance_Record2 = new HashSet<Material_Maintenance_Record>();
            this.Fixture_Part_Order_M = new HashSet<Fixture_Part_Order_M>();
            this.Fixture_Part_Order_M1 = new HashSet<Fixture_Part_Order_M>();
            this.Fixture_Part_Order_M2 = new HashSet<Fixture_Part_Order_M>();
            this.Machine_Station = new HashSet<Machine_Station>();
            this.Machine_Station1 = new HashSet<Machine_Station>();
            this.Machine_Station2 = new HashSet<Machine_Station>();
            this.Machine_Customer = new HashSet<Machine_Customer>();
            this.Machine_Customer1 = new HashSet<Machine_Customer>();
            this.Machine_Customer2 = new HashSet<Machine_Customer>();
            this.GL_LineHistory = new HashSet<GL_LineHistory>();
            this.GL_LineHistory1 = new HashSet<GL_LineHistory>();
            this.GL_LineHistory2 = new HashSet<GL_LineHistory>();
            this.Current_Manpower = new HashSet<Current_Manpower>();
            this.Current_Manpower1 = new HashSet<Current_Manpower>();
            this.DemissionRateAndWorkSchedule = new HashSet<DemissionRateAndWorkSchedule>();
            this.DemissionRateAndWorkSchedule1 = new HashSet<DemissionRateAndWorkSchedule>();
            this.RP_Demand_Calculation_Record = new HashSet<RP_Demand_Calculation_Record>();
            this.RP_Demand_Calculation_Record1 = new HashSet<RP_Demand_Calculation_Record>();
            this.RP_Flowchart_Detail_ME = new HashSet<RP_Flowchart_Detail_ME>();
            this.RP_Flowchart_Master = new HashSet<RP_Flowchart_Master>();
            this.RP_Flowchart_Master1 = new HashSet<RP_Flowchart_Master>();
            this.System_Project = new HashSet<System_Project>();
            this.GL_StationHistory = new HashSet<GL_StationHistory>();
            this.GL_StationHistory1 = new HashSet<GL_StationHistory>();
            this.GL_StationHistory2 = new HashSet<GL_StationHistory>();
            this.GL_Line = new HashSet<GL_Line>();
            this.GL_Line1 = new HashSet<GL_Line>();
            this.GL_Line2 = new HashSet<GL_Line>();
            this.OEE_StationDefectCode = new HashSet<OEE_StationDefectCode>();
            this.OEE_StationDefectCode1 = new HashSet<OEE_StationDefectCode>();
            this.OEE_StationDefectCode2 = new HashSet<OEE_StationDefectCode>();
            this.OEE_UserStation = new HashSet<OEE_UserStation>();
            this.OEE_UserStation1 = new HashSet<OEE_UserStation>();
            this.OEE_UserStation2 = new HashSet<OEE_UserStation>();
            this.Fixture_M = new HashSet<Fixture_M>();
            this.Fixture_M1 = new HashSet<Fixture_M>();
            this.Fixture_M2 = new HashSet<Fixture_M>();
            this.Fixture_Part = new HashSet<Fixture_Part>();
            this.Fixture_Part1 = new HashSet<Fixture_Part>();
            this.Fixture_Part2 = new HashSet<Fixture_Part>();
            this.Fixture_Part_Setting_M = new HashSet<Fixture_Part_Setting_M>();
            this.Fixture_Part_Setting_M1 = new HashSet<Fixture_Part_Setting_M>();
            this.Fixture_Part_Setting_M2 = new HashSet<Fixture_Part_Setting_M>();
            this.OEE_DefectCodeDailySum = new HashSet<OEE_DefectCodeDailySum>();
            this.OEE_DefectCodeDailySum1 = new HashSet<OEE_DefectCodeDailySum>();
            this.OEE_DefectCodeDailySum2 = new HashSet<OEE_DefectCodeDailySum>();
            this.OEE_StationDailyDownSum = new HashSet<OEE_StationDailyDownSum>();
            this.OEE_StationDailyDownSum1 = new HashSet<OEE_StationDailyDownSum>();
            this.OEE_StationDailyDownSum2 = new HashSet<OEE_StationDailyDownSum>();
            this.CNCMachine = new HashSet<CNCMachine>();
            this.CNCMachine1 = new HashSet<CNCMachine>();
            this.CNCMachine2 = new HashSet<CNCMachine>();
            this.GL_ShiftTime = new HashSet<GL_ShiftTime>();
            this.GL_ShiftTime1 = new HashSet<GL_ShiftTime>();
            this.GL_ShiftTime2 = new HashSet<GL_ShiftTime>();
            this.PlayBoard_Setting = new HashSet<PlayBoard_Setting>();
            this.PlayBoard_Setting1 = new HashSet<PlayBoard_Setting>();
            this.PlayBoard_Setting2 = new HashSet<PlayBoard_Setting>();
            this.Equipment_Info = new HashSet<Equipment_Info>();
            this.Equipment_Info1 = new HashSet<Equipment_Info>();
            this.Equipment_Info2 = new HashSet<Equipment_Info>();
            this.OEE_MachineInfo = new HashSet<OEE_MachineInfo>();
            this.OEE_MachineInfo1 = new HashSet<OEE_MachineInfo>();
            this.OEE_MachineInfo2 = new HashSet<OEE_MachineInfo>();
            this.Fixture_Machine = new HashSet<Fixture_Machine>();
            this.Fixture_Machine1 = new HashSet<Fixture_Machine>();
            this.Fixture_Machine2 = new HashSet<Fixture_Machine>();
            this.Fixture_Return_M = new HashSet<Fixture_Return_M>();
            this.Fixture_Return_M1 = new HashSet<Fixture_Return_M>();
            this.Fixture_Return_M2 = new HashSet<Fixture_Return_M>();
            this.OEE_DefectCodeDailyNum = new HashSet<OEE_DefectCodeDailyNum>();
            this.OEE_DefectCodeDailyNum1 = new HashSet<OEE_DefectCodeDailyNum>();
            this.OEE_DefectCodeDailyNum2 = new HashSet<OEE_DefectCodeDailyNum>();
            this.OEE_DownTimeCode = new HashSet<OEE_DownTimeCode>();
            this.OEE_DownTimeCode1 = new HashSet<OEE_DownTimeCode>();
            this.OEE_DownTimeCode2 = new HashSet<OEE_DownTimeCode>();
            this.OEE_DownTimeType = new HashSet<OEE_DownTimeType>();
            this.OEE_DownTimeType1 = new HashSet<OEE_DownTimeType>();
            this.OEE_DownTimeType2 = new HashSet<OEE_DownTimeType>();
            this.OEE_EveryDayDFcodeMissing = new HashSet<OEE_EveryDayDFcodeMissing>();
            this.OEE_EveryDayDFcodeMissing1 = new HashSet<OEE_EveryDayDFcodeMissing>();
            this.OEE_EveryDayDFcodeMissing2 = new HashSet<OEE_EveryDayDFcodeMissing>();
            this.CostCtr_info = new HashSet<CostCtr_info>();
            this.CostCtr_info1 = new HashSet<CostCtr_info>();
            this.CostCtr_info2 = new HashSet<CostCtr_info>();
            this.GL_Station = new HashSet<GL_Station>();
            this.GL_Station1 = new HashSet<GL_Station>();
            this.GL_Station2 = new HashSet<GL_Station>();
            this.OEE_EveryDayMachine = new HashSet<OEE_EveryDayMachine>();
            this.OEE_EveryDayMachine1 = new HashSet<OEE_EveryDayMachine>();
            this.OEE_EveryDayMachine2 = new HashSet<OEE_EveryDayMachine>();
            this.OEE_MachineDailyDownRecord = new HashSet<OEE_MachineDailyDownRecord>();
            this.OEE_MachineDailyDownRecord1 = new HashSet<OEE_MachineDailyDownRecord>();
            this.OEE_MachineDailyDownRecord2 = new HashSet<OEE_MachineDailyDownRecord>();
            this.GL_LineGroup = new HashSet<GL_LineGroup>();
            this.GL_LineGroup1 = new HashSet<GL_LineGroup>();
            this.GL_LineGroup2 = new HashSet<GL_LineGroup>();
            this.OEE_ImprovementPlan = new HashSet<OEE_ImprovementPlan>();
            this.OEE_ImprovementPlan1 = new HashSet<OEE_ImprovementPlan>();
            this.OEE_ImprovementPlan2 = new HashSet<OEE_ImprovementPlan>();
            this.OEE_MeetingTypeInfo = new HashSet<OEE_MeetingTypeInfo>();
            this.OEE_MeetingTypeInfo1 = new HashSet<OEE_MeetingTypeInfo>();
            this.OEE_MeetingTypeInfo2 = new HashSet<OEE_MeetingTypeInfo>();
            this.OEE_MetricInfo = new HashSet<OEE_MetricInfo>();
            this.OEE_MetricInfo1 = new HashSet<OEE_MetricInfo>();
            this.OEE_MetricInfo2 = new HashSet<OEE_MetricInfo>();
            this.GL_MeetingTypeInfo = new HashSet<GL_MeetingTypeInfo>();
            this.GL_MeetingTypeInfo1 = new HashSet<GL_MeetingTypeInfo>();
            this.GL_MeetingTypeInfo2 = new HashSet<GL_MeetingTypeInfo>();
            this.GL_MetricInfo = new HashSet<GL_MetricInfo>();
            this.GL_MetricInfo1 = new HashSet<GL_MetricInfo>();
            this.GL_MetricInfo2 = new HashSet<GL_MetricInfo>();
            this.GL_ActionTasker = new HashSet<GL_ActionTasker>();
            this.GL_ActionTasker1 = new HashSet<GL_ActionTasker>();
            this.GL_ActionTasker2 = new HashSet<GL_ActionTasker>();
        }
    
        public int Organization_UID { get; set; }
        public string Organization_ID { get; set; }
        public string Organization_Name { get; set; }
        public string Organization_Desc { get; set; }
        public string OrgManager_Name { get; set; }
        public string OrgManager_Tel { get; set; }
        public string OrgManager_Email { get; set; }
        public string Cost_Center { get; set; }
        public System.DateTime Begin_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQP_Type> EQP_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQP_Type> EQP_Type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_Master> FlowChart_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Demand_Summary> Material_Demand_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Demand_Summary> Material_Demand_Summary1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Repair_Demand> Material_Repair_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Repair_Demand> Material_Repair_Demand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Spareparts_Demand> Material_Spareparts_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Spareparts_Demand> Material_Spareparts_Demand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Function_Plant> System_Function_Plant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Function_Plant> System_Function_Plant1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_OrganizationBOM> System_OrganizationBOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_OrganizationBOM> System_OrganizationBOM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_UserOrg> System_UserOrg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_UserOrg> System_UserOrg1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_UserOrg> System_UserOrg2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_UserOrg> System_UserOrg3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_UserOrg> System_UserOrg4 { get; set; }
        public virtual System_BU_D_Org System_BU_D_Org { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Normal_Demand> Material_Normal_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Normal_Demand> Material_Normal_Demand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectCode_Group> DefectCode_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectCode_Group> DefectCode_Group1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectCode_Group> DefectCode_Group2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectCode_RepairSolution> DefectCode_RepairSolution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectCode_RepairSolution> DefectCode_RepairSolution1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectCode_RepairSolution> DefectCode_RepairSolution2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_DefectCode> Fixture_DefectCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_DefectCode> Fixture_DefectCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_DefectCode> Fixture_DefectCode2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Profile> Fixture_Maintenance_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Profile> Fixture_Maintenance_Profile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Maintenance_Profile> Fixture_Maintenance_Profile2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_RepairSolution> Fixture_RepairSolution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_RepairSolution> Fixture_RepairSolution1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_RepairSolution> Fixture_RepairSolution2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixtureDefectCode_Setting> FixtureDefectCode_Setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixtureDefectCode_Setting> FixtureDefectCode_Setting1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixtureDefectCode_Setting> FixtureDefectCode_Setting2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Process_Info> Process_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Process_Info> Process_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Process_Info> Process_Info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production_Line> Production_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production_Line> Production_Line1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production_Line> Production_Line2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair_Location> Repair_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair_Location> Repair_Location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair_Location> Repair_Location2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Info> Vendor_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Info> Vendor_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workshop> Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workshop> Workshop1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workshop> Workshop2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkStation> WorkStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkStation> WorkStation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkStation> WorkStation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Plan> Maintenance_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Plan> Maintenance_Plan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Plan> Maintenance_Plan2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_M> Fixture_Repair_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_M> Fixture_Repair_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Repair_M> Fixture_Repair_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Totake_M> Fixture_Totake_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Totake_M> Fixture_Totake_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Totake_M> Fixture_Totake_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Warehouse_Storage> Fixture_Warehouse_Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Warehouse_Storage> Fixture_Warehouse_Storage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Warehouse_Storage> Fixture_Warehouse_Storage2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Module> System_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Email_Delivery> System_Email_Delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Email_Delivery> System_Email_Delivery1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Warehouse> Fixture_Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Warehouse> Fixture_Warehouse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Warehouse> Fixture_Warehouse2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Schedule> System_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_M> Fixture_Part_Demand_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_M> Fixture_Part_Demand_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_M> Fixture_Part_Demand_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_Summary_M> Fixture_Part_Demand_Summary_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_Summary_M> Fixture_Part_Demand_Summary_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Demand_Summary_M> Fixture_Part_Demand_Summary_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQP_UserTable> EQP_UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Info> Material_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Maintenance_Record> Material_Maintenance_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Maintenance_Record> Material_Maintenance_Record1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Maintenance_Record> Material_Maintenance_Record2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Order_M> Fixture_Part_Order_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Order_M> Fixture_Part_Order_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Order_M> Fixture_Part_Order_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Station> Machine_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Station> Machine_Station1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Station> Machine_Station2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Customer> Machine_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Customer> Machine_Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Customer> Machine_Customer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineHistory> GL_LineHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineHistory> GL_LineHistory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineHistory> GL_LineHistory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Current_Manpower> Current_Manpower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Current_Manpower> Current_Manpower1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemissionRateAndWorkSchedule> DemissionRateAndWorkSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemissionRateAndWorkSchedule> DemissionRateAndWorkSchedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Demand_Calculation_Record> RP_Demand_Calculation_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Demand_Calculation_Record> RP_Demand_Calculation_Record1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Detail_ME> RP_Flowchart_Detail_ME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Master> RP_Flowchart_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RP_Flowchart_Master> RP_Flowchart_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Project> System_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StationHistory> GL_StationHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StationHistory> GL_StationHistory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_StationHistory> GL_StationHistory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Line> GL_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Line> GL_Line1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Line> GL_Line2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDefectCode> OEE_StationDefectCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDefectCode> OEE_StationDefectCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDefectCode> OEE_StationDefectCode2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_UserStation> OEE_UserStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_UserStation> OEE_UserStation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_UserStation> OEE_UserStation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_M> Fixture_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_M> Fixture_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_M> Fixture_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part> Fixture_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part> Fixture_Part1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part> Fixture_Part2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Setting_M> Fixture_Part_Setting_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Setting_M> Fixture_Part_Setting_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Part_Setting_M> Fixture_Part_Setting_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DefectCodeDailySum> OEE_DefectCodeDailySum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DefectCodeDailySum> OEE_DefectCodeDailySum1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DefectCodeDailySum> OEE_DefectCodeDailySum2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDailyDownSum> OEE_StationDailyDownSum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDailyDownSum> OEE_StationDailyDownSum1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_StationDailyDownSum> OEE_StationDailyDownSum2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNCMachine> CNCMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNCMachine> CNCMachine1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNCMachine> CNCMachine2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ShiftTime> GL_ShiftTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ShiftTime> GL_ShiftTime1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ShiftTime> GL_ShiftTime2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayBoard_Setting> PlayBoard_Setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayBoard_Setting> PlayBoard_Setting1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayBoard_Setting> PlayBoard_Setting2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Info> Equipment_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Info> Equipment_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Info> Equipment_Info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineInfo> OEE_MachineInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineInfo> OEE_MachineInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineInfo> OEE_MachineInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Machine> Fixture_Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Machine> Fixture_Machine1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Machine> Fixture_Machine2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Return_M> Fixture_Return_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Return_M> Fixture_Return_M1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixture_Return_M> Fixture_Return_M2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DefectCodeDailyNum> OEE_DefectCodeDailyNum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DefectCodeDailyNum> OEE_DefectCodeDailyNum1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DefectCodeDailyNum> OEE_DefectCodeDailyNum2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeCode> OEE_DownTimeCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeCode> OEE_DownTimeCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeCode> OEE_DownTimeCode2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeType> OEE_DownTimeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeType> OEE_DownTimeType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_DownTimeType> OEE_DownTimeType2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_EveryDayDFcodeMissing> OEE_EveryDayDFcodeMissing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_EveryDayDFcodeMissing> OEE_EveryDayDFcodeMissing1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_EveryDayDFcodeMissing> OEE_EveryDayDFcodeMissing2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCtr_info> CostCtr_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCtr_info> CostCtr_info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCtr_info> CostCtr_info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Station> GL_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Station> GL_Station1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Station> GL_Station2 { get; set; }
        public virtual System_Users System_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_EveryDayMachine> OEE_EveryDayMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_EveryDayMachine> OEE_EveryDayMachine1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_EveryDayMachine> OEE_EveryDayMachine2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineDailyDownRecord> OEE_MachineDailyDownRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineDailyDownRecord> OEE_MachineDailyDownRecord1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MachineDailyDownRecord> OEE_MachineDailyDownRecord2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineGroup> GL_LineGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineGroup> GL_LineGroup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_LineGroup> GL_LineGroup2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_ImprovementPlan> OEE_ImprovementPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_ImprovementPlan> OEE_ImprovementPlan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_ImprovementPlan> OEE_ImprovementPlan2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MeetingTypeInfo> OEE_MeetingTypeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MeetingTypeInfo> OEE_MeetingTypeInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MeetingTypeInfo> OEE_MeetingTypeInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MetricInfo> OEE_MetricInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MetricInfo> OEE_MetricInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEE_MetricInfo> OEE_MetricInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MeetingTypeInfo> GL_MeetingTypeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MeetingTypeInfo> GL_MeetingTypeInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MeetingTypeInfo> GL_MeetingTypeInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MetricInfo> GL_MetricInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MetricInfo> GL_MetricInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_MetricInfo> GL_MetricInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ActionTasker> GL_ActionTasker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ActionTasker> GL_ActionTasker1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_ActionTasker> GL_ActionTasker2 { get; set; }
    }
}
