//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwoHoursCapacityHistory
    {
        public int TwoHoursCapacity_UID { get; set; }
        public string EQPID { get; set; }
        public string Project { get; set; }
        public string Process { get; set; }
        public Nullable<int> CycleTime { get; set; }
        public Nullable<int> PlanQty { get; set; }
        public Nullable<int> OutputQty1 { get; set; }
        public Nullable<int> OutputQty2 { get; set; }
        public Nullable<int> OutputQty3 { get; set; }
        public Nullable<int> OutputQty4 { get; set; }
        public Nullable<int> OutputQty5 { get; set; }
        public Nullable<int> OutputQty6 { get; set; }
        public string Shifts { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
