//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warning_List
    {
        public int Warning_UID { get; set; }
        public string Warning_Types { get; set; }
        public string Customer { get; set; }
        public string Project { get; set; }
        public string Part_Types { get; set; }
        public string Product_Phase { get; set; }
        public System.DateTime Product_Date { get; set; }
        public string Time_Interval { get; set; }
        public int FncPlant_Now { get; set; }
        public int FncPlant_Effect { get; set; }
    
        public virtual System_Function_Plant System_Function_Plant { get; set; }
        public virtual System_Function_Plant System_Function_Plant1 { get; set; }
    }
}
