//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIP_Change_History
    {
        public int Change_UID { get; set; }
        public string Change_Type { get; set; }
        public int Product_UID { get; set; }
        public Nullable<int> WIP_Old { get; set; }
        public Nullable<int> WIP_Add { get; set; }
        public string Comment { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public int FlowChart_Detail_UID { get; set; }
    
        public virtual System_Users System_Users { get; set; }
    }
}
